# -*- coding: utf-8 -*-
"""People data module 3/9: P-0018, P-0020..P-0026 (P-0019 Gyegwi removed 2026-08-17: 雞貴 is Yijing's ethnonym for the Korean people, not a person). Compiled 2026-08-16 from verified web research."""
D = "2026-08-16"

PEOPLE_3 = [
dict(id="P-0018", full="Hyeryun", variants="慧輪",
     hangul="혜륜", hanja="慧輪", indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="KOREAN (Silla; reading per Kim Bok-soon; Yijing wrote 高麗)", period="ANCIENT",
     role="Pilgrim monk",
     religion="Buddhism",
     india="Included in Yijing's Da Tang Xiyu qiufa gaoseng zhuan among Korean monks",
     korea="Korean monk; linked to the 高麗-雞貴 identification question",
     rel="DIRECT", travel="YES",
     tsum="Korea -> (per Yijing) India route network",
     dir="KOREA_TO_INDIA", exch="RELIGIOUS",
     evid="Yijing's Da Tang Xiyu qiufa gaoseng zhuan; KCI scholarship (Kim Bok-soon)",
     sig="Contributes to the documented Korean monastic presence in Yijing's India network",
     conf="MEDIUM", status="PARTIAL",
      notes="Identification as Silla vs Koguryo/Goryeo debated (Yijing wrote '高麗'). Note: Yijing's 雞貴 gloss ('矩矩吒是雞，醫說羅是貴，即高麗國也') is an ethnonym for the Korean people, not a monk - the former P-0019 record was removed on that basis.",
      srcs=["kci_kimboksoon","historylibrary_silla","yijing_wikisource"], date=D),

# P-0019 REMOVED 2026-08-17: 'Gyegwi' (雞貴) is not a person. Yijing's Da Tang Xiyu
# qiufa gaoseng zhuan glosses 雞貴 as an ethnonym for the Korean people: '矩矩吒是雞,
# 醫說羅是貴，即高麗國也' ('Kukkuta' = cock; 'uisolla' = gui; this is the Koguryo/Goryeo
# country, whose people honor cocks). Corresponding travel record T-0040 was deleted
# from data_links_1.py; see docs/unresolved_cases.md. Reuse ID P-0019 only with care.

dict(id="P-0020", full="Ojin", variants="悟真",
     hangul="오진", hanja="悟真", indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="KOREAN (Silla)", period="ANCIENT",
     role="Esoteric Buddhist monk",
     religion="Buddhism (Esoteric)",
     inst="Tang (Chang'an) milieu; studied under Hyegwa (慧果)",
     india="Went to Tang with Hyeil (惠日, c. 789, King Wonseong era); went to Central India and died in Tibet",
     korea="Silla esoteric monk; part of the Amoghavajra-lineage transmission to Silla",
     rel="DIRECT", travel="YES",
     tsum="Silla -> Tang -> Central India -> Tibet (death)",
     dir="KOREA_TO_INDIA", exch="RELIGIOUS",
     evid="KCI scholarship (Ko Young-seop on Lamotte); EncyKorea '밀교'",
     sig="Documented late-8th-century Silla monk who reached Central India",
     conf="MEDIUM", status="VERIFIED", notes="NULL",
     srcs=["kci_ko","encykorea_milgyo"], date=D),

dict(id="P-0021", full="Wonpyo", variants="원표 (元表 in some transcriptions)",
     hangul="원표", hanja=None, indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="KOREAN (Unified Silla)", period="ANCIENT",
     role="Monk",
     religion="Buddhism",
     india="Travelled to India via Tang (King Gyeongdeok era, 742-765); returned to Tang and died in China",
     korea="Unified Silla monk",
     rel="DIRECT", travel="YES",
     tsum="Silla -> Tang -> India -> Tang (death in China)",
     dir="KOREA_TO_INDIA", exch="RELIGIOUS",
     evid="KCI scholarship (Ko Young-seop on Lamotte)",
     sig="Documented 8th-century Unified Silla monk who reached India",
     conf="MEDIUM", status="VERIFIED",
     notes="Transcription varies (원표/元表).",
     srcs=["kci_ko"], date=D),

dict(id="P-0022", full="Hyŏnyu", variants="賢遊? (transcription uncertain)",
     hangul="현유", hanja=None, indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="KOREAN (Goguryeo)", period="ANCIENT",
     role="Monk",
     religion="Buddhism",
     india="Followed Chinese monk Sengche (僧哲) to Sri Lanka and was ordained there (South Asian connection; not mainland India)",
     korea="Goguryeo monk",
     rel="DIRECT", travel="YES",
     tsum="Goguryeo -> (via China) -> Sri Lanka; ordained there",
     dir="UNCERTAIN", exch="RELIGIOUS",
     evid="KCI scholarship (Ko Young-seop on Lamotte)",
     sig="Documented Korean monk in the South Asian monastic world (Sri Lanka) in the 7th century",
     conf="MEDIUM", status="PARTIAL",
     notes="Connection is to Sri Lanka rather than mainland India; direction of influence for India-Korea exchange uncertain.",
     srcs=["kci_ko"], date=D),

dict(id="P-0023", full="Dhyānabhadra", variants="Jikong (指空); Shikong; Śūnyadiśya-Dhyānabhadra; Zhikong Chanxian",
     hangul="지공", hanja="指空", indian="Śūnyadiśya-Dhyānabhadra",
     birth=1289, birthp="APPROX", death=1363, deathp="YEAR",
     nat="INDIAN (Magadha)", period="MEDIEVAL",
     role="Indian Buddhist master; Seon/Chan patriarch",
     religion="Buddhism (Chan/Seon transmission)",
     inst="Ordained at Nalanda; founded Hoeamsa (회암사) 1328",
     india="Born in Magadha (Indian royal family per tradition); ordained at Nalanda; famous in India before leaving",
     korea="Invited by King Ch'ungsuk (met at Mongol court); came to Goryeo 1326; founded Hoeamsa 1328 (reportedly modeled on Nalanda); influenced Korean Seon students incl. Naong Hyegeun and Muhak Chach'o; King Kongmin later sent his relics to Goryeo",
     rel="DIRECT", travel="YES",
     tsum="Magadha -> (Tibet) -> Yuan China -> Goryeo (1326) -> Yuan China; died 1363 (relics sent to Goryeo)",
     dir="INDIA_TO_KOREA", exch="RELIGIOUS;INTELLECTUAL;CULTURAL",
     evid="Hagiographical and scholastic records; temple foundation (Hoeamsa 1328); lineage transmission to Naong and Muhak",
     sig="The last great Indian monk active in Korea; key figure in late-Goryeo Seon formation",
      conf="HIGH", status="VERIFIED",
      notes="Biography contains hagiographical elements (Indian royal family per tradition; ordained at Nalanda at age 8, completed training at 19 - per Yangju Hoeamsa museum and stele tradition). Core facts standard across sources: Magadha -> Yuan Dadu -> Goryeo 1326 (Ch'ungsuk era) -> Dadu Beopwonsa; died 1363; Hoeamsa stupa erected 1372 (壬子; stele text by Yi Saek).",
      srcs=["eob_zhikong","wiki_dhyana","yangju_museum_jigong","encykorea_jigong","nrich_jigong_stele"], date=D),

dict(id="P-0024", full="Naong Hyegeun", variants="懶翁 惠勤",
     hangul="나옹 혜근", hanja="懶翁惠勤", indian=None,
     birth=1320, birthp="YEAR", death=1376, deathp="YEAR",
     nat="KOREAN (Goryeo)", period="MEDIEVAL",
     role="Seon monk",
     religion="Buddhism (Seon)",
     inst="Sungsusa; Wangryunsa milieu",
     india="Received bodhisattva precepts from the Indian master Dhyānabhadra (Jikong) at age 7 (at Sungsusa) and met him again in Yuan China at age 38, receiving Jikong's exhortation to return to Korea",
     korea="Major Goryeo Seon master; successor-influence of Jikong's lineage",
     rel="MEDIATED", travel="NO",
     tsum="Travelled to Yuan China (not India); India connection entirely mediated through Jikong",
     dir="INDIA_TO_KOREA", exch="RELIGIOUS",
     evid="KCI scholarship (Ko Young-seop on Lamotte) documenting the Jikong-Naong relationship",
     sig="The channel through which the Indian monk Dhyānabhadra's teaching entered mainstream Goryeo Seon",
     conf="MEDIUM", status="VERIFIED",
     notes="No personal travel to India; relationship mediated via the Indian master Jikong.",
     srcs=["kci_ko"], date=D),

dict(id="P-0025", full="Yi Su-gwang", variants="Yi Sugwang; Lee Soo-kwang; pen name Jibong (芝峰)",
     hangul="이수광", hanja="李睟光", indian=None,
     birth=1563, birthp="YEAR", death=1628, deathp="YEAR",
     nat="KOREAN (Joseon)", period="EARLY_MODERN",
     role="Scholar-official; encyclopedist; envoy to Ming China",
     religion="Confucian",
     inst="Joseon court; 1609-1611 mission to Ming",
     india="Compiled the Foreign Countries (外國) section of Jibong yuseol with entries on India-linked polities - Bengal (榜葛剌), Ceylon (錫蘭山), Calicut (古俚) - based on Ming-era Chinese sources; among the earliest organized channels of India-related geographic knowledge into Joseon",
     korea="National cultural figure; Jibong yuseol (1614) is the foundational Korean encyclopedia",
     rel="MEDIATED", travel="NO",
     tsum="Travelled to Ming China (1609-11); never to India",
     dir="INDIA_TO_KOREA", exch="INTELLECTUAL;CULTURAL",
     evid="Jibong yuseol Foreign Countries section; Yeungnam University Press scholarly edition",
     sig="First systematic Joseon-era encyclopedic intake of Indian subcontinent geography",
     conf="HIGH", status="VERIFIED",
     notes="India content enters via Chinese-world geography, not direct observation.",
     srcs=["wiki_yisugwang","yu_press"], date=D),

dict(id="P-0026", full="Yi Kyu-gyŏng", variants="Yi Kyugyong",
     hangul="이규경", hanja="李圭景", indian=None,
      birth=1788, birthp="YEAR", death=1856, deathp="YEAR",
     nat="KOREAN (Joseon)", period="EARLY_MODERN",
     role="Silhak scholar; encyclopedist",
     religion="Confucian",
     inst="None (private scholar)",
     india="UNCERTAIN - his encyclopedia Oju yŏnmun changjŏn san'go (60 books, 1,417 topics; ~80 items on Western learning and world geography) plausibly contains India-related entries, but no specific India entry was verified in this pilot",
     korea="One of Joseon's greatest encyclopedists; Oju is a national cultural monument",
     rel="UNCERTAIN", travel="NO",
     tsum="Did not travel abroad",
     dir="UNCERTAIN", exch="INTELLECTUAL",
     evid="NULL (India-specific entries not yet located)",
     sig="Representative late-Joseon encyclopedic frame for absorbing world (incl. Asian) knowledge",
     conf="LOW", status="PARTIAL",
      notes="Born 1788-08-05, died 1856-05-16 (Korean Wikipedia; lunar dates). Follow-up needed: locate India entries (e.g., 天竺, 佛國) inside Oju itself.",
      srcs=["wiki_yikyugyong","wiki_oju","ko_wiki_yikyugyong"], date=D),
]
