# -*- coding: utf-8 -*-
"""People data module 8/9: P-0068..P-0075 (unresolved candidates + Vinoba Bhave + Yi Yŏng-jae + Hwang Su-yŏng + Jikong-circle disciples). Compiled 2026-08-17."""
D = "2026-08-17"

PEOPLE_8 = [
dict(id="P-0068", full="Sŏ Chŏng-ju", variants="Seo Jeong-ju; pen name Midang (未堂)",
     hangul="서정주", hanja="徐廷柱", indian=None,
     birth=1915, birthp="DAY", death=2000, deathp="DAY",
     nat="KOREAN (colonial Korea -> South Korea)", period="CONTEMPORARY",
     role="Poet; educator (Dongguk/Kyonggi university professor)",
     religion="Buddhism (studied at Gaewunsa; Dongguk Buddhist college)",
     inst="Dongguk University (professor)",
     india="Met Indian poet Sitanshu Yashaschandra at Dongguk University (visit date unstated; article reposted 2010-08-11): the two discussed the mainstream and current state of Indian poetry and Korean-Indian literary exchange; Yashaschandra praised Sŏ's poem Hwasa (화사) for its compassion (자비심); they proposed mutual poetry translation and a '자비회' (Compassion Society) literary body",
     korea="One of Korea's most influential 20th-century poets (Hwasajip, Guksoto, Jilmajae Sinhwa); professor and Dean of the College of Liberal Arts (문리대학장) at Dongguk University; president of the Korean Writers Association (한국문인협회)",
     rel="DIRECT", travel="NO",
     tsum="India -> Korea: Yashaschandra visited Dongguk University and met Sŏ Chŏng-ju (year unstated)",
     dir="INDIA_TO_KOREA", exch="INTELLECTUAL",
     evid="Dongguk University newspaper (동대신문) interview article '[휴게실] 徐廷柱敎授, 印度詩人 야산챤드라 와' (reposted 2010-08-11)",
     sig="Major Korean poet; documented literary encounter with an Indian poet at a Buddhist university; contested historical legacy (pro-Japanese activity)",
     conf="MEDIUM", status="VERIFIED",
     notes="REVIEW closed 2026-08-17: India link now documented (Dongguk newspaper interview with Sitanshu Yashaschandra). Original article date not stated - Sŏ served as 문리대학장 in the 1970s, so the visit is placed in B5 with year unknown; literary exchange (not Buddhist-institutional); classified SECONDARY/ADAPT.",
     srcs=["wiki_seo","donggukmedia_seo_yashaschandra"], date=D),

dict(id="P-0069", full="Hwang Tong-gyu", variants="Hwang Dong-gyu; 黃東奎",
     hangul="황동규", hanja="黃東奎", indian=None,
     birth=1938, birthp="DAY", death=None, deathp="UNKNOWN",
     nat="KOREAN (South Korea)", period="CONTEMPORARY",
     role="Poet; English-literature scholar; Professor Emeritus (Seoul National University)",
     religion="Protestant (Presbyterian)",
     inst="Seoul National University (emeritus)",
     india="NONE FOUND - education documented only in Korea, US (Iowa), UK (Edinburgh)",
     korea="Major contemporary Korean poet; son of novelist Hwang Sun-won; Hoam Prize (2016)",
     rel="UNCERTAIN", travel="UNCERTAIN",
     tsum="NULL", dir="UNCERTAIN", exch="NULL",
     evid="NULL",
     sig="Leading Korean poet and English literature scholar",
     conf="LOW", status="UNRESOLVED",
     notes="Named as a candidate; no India link documented in searched sources (his international academic stays were US/UK).",
     srcs=["wiki_hwang"], date=D),

dict(id="P-0070", full="Kim Chi-ha", variants="Kim Ji-ha; 金芝河; birth name Kim Yeong-il",
     hangul="김지하", hanja="金芝河", indian=None,
     birth=1941, birthp="DAY", death=2022, deathp="DAY",
     nat="KOREAN (South Korea)", period="CONTEMPORARY",
     role="Poet; thinker (originator of the 'Life Philosophy' 생명사상); professor (Dongguk/Wonkwang)",
     religion="Catholic (baptismal name Francisco); later synthesized Buddhism, Confucianism, Donghak",
     inst="Dongguk University; Wonkwang University",
     india="NONE VERIFIED - the popular association of his 'life thought' with Gandhi/ahimsa appears in discourse but NO source could be located; his documented thought synthesizes Christianity, Buddhism (Maitreya, Avatamsaka), Confucianism, and Donghak",
     korea="Iconic participatory poet of the 1970s democratic movement (오적), later life-philosophy thinker",
     rel="UNCERTAIN", travel="UNCERTAIN",
     tsum="NULL", dir="UNCERTAIN", exch="NULL",
     evid="Hani 2026-07-03 (임진택 interview on '김지하를 다시 본다'): thought rooted in Donghak (시천주/향아설위), 증산도 개벽사상, Buddhism, Christianity",
     sig="Major Korean poet; systematized Korean 'life philosophy' merging Eastern traditions",
     conf="LOW", status="UNRESOLVED",
     notes="REVIEW closed 2026-08-17 as documented negative: the authoritative Hani interview documents the life philosophy as Donghak-rooted with no Gandhi/India influence; popular Gandhi/ahimsa association remains unverified; classified NONE/EXCLUDE.",
     srcs=["wiki_kimchiha","mokpo_kimchiha","hani_kimchiha_2026"], date=D),

dict(id="P-0071", full="Vinoba Bhave", variants="Acharya Vinoba Bhave; विनोबा भावे",
     hangul=None, hanja=None, indian="विनोबा भावे",
     birth=1895, birthp="YEAR", death=1982, deathp="YEAR",
     nat="INDIAN", period="CONTEMPORARY",
     role="Gandhian philosopher; leader of the Bhoodan (land-gift) movement; spiritual successor of Gandhi",
     religion="Hindu (Gandhian)",
     inst="Bhoodan movement; Sarvodaya",
     india="Major Gandhian leader; his ashram was visited by Korean monk Pŏpchŏng in 1971",
     korea="Met Korean Buddhist monk Pŏpchŏng (1971) at his ashram in India; the encounter transmitted Gandhian renunciation philosophy to Korea via Pŏpchŏng's essays",
     rel="DIRECT", travel="NO",
     tsum="Never visited Korea; the encounter happened in India",
     dir="INDIA_TO_KOREA", exch="RELIGIOUS;INTELLECTUAL",
     evid="Bulkwang article (2024) on Pŏpchŏng's India trip and the Vinoba Bhave meeting",
     sig="The Indian intermediary through whom Gandhian simplicity reached mainstream Korean Buddhist thought",
     conf="MEDIUM", status="VERIFIED",
     notes="Included because he is the documented Indian counterpart in Pŏpchŏng's 1971 India encounter.",
     srcs=["bulkwang_beopjeong"], date=D),

dict(id="P-0072", full="Yi Yŏng-jae", variants="Lee Young-jae; Yi Yeong-jae; dharma names Paekkwang (白光), Pŏmnan (梵鸞), Chongwŏn (宗圓)",
     hangul="이영재", hanja="李英宰", indian=None,
     birth=1900, birthp="YEAR", death=1927, deathp="DAY",
     nat="KOREAN (colonial Korea)", period="MODERN",
     role="Monk (유학승); Buddhist reformer; first modern-era Korean monk to attempt an India pilgrimage",
     religion="Buddhism (ordained 1918 at Beopjusa; studied under Nampa and Paek Ch'owŏl sunims)",
     inst="Beopjusa; Nihon University; Tokyo Imperial University",
     india="First modern-era Korean Buddhist pilgrimage attempt (1925): studied Sanskrit/Pali (Indian Philosophy) at Tokyo Imperial University; departed Yokohama 1925-11-09 for Ceylon (Sri Lanka) intending 2 years of study then an India pilgrimage; died in Ceylon 1927-10-12 before reaching India proper",
     korea="Colonial-era Buddhist reformer: '조선불교혁신론' (27 installments, Chosun Ilbo 1922); led the 조선불교동경유학생회 journal 금강저 (1924); travelogues 도석기/남국기/석란의 불교",
     rel="DIRECT", travel="YES",
     tsum="Korea -> Japan (study 1918-1925) -> Ceylon (Sri Lanka) Dec 1925; intended India pilgrimage; died in Ceylon 1927-10-12",
     dir="KOREA_TO_INDIA", exch="RELIGIOUS;INTELLECTUAL",
     evid="Ibulgyo 2021-02-03 biography (한국불교 격동 100년 series); Dong-A Ilbo 1927-10-27 obituary; KCI ART003193373; Beopbo series entry",
     sig="Pioneer of modern Korea-India Buddhist engagement: first Korean monk in centuries to set out for India; his vow and writings mark the start of the modern pilgrimage era",
     conf="HIGH", status="VERIFIED",
     notes="Never reached India proper - died in Ceylon aged 28; Dong-A Ilbo (1927-10-27) called him the first Korean monk in several hundred years to go to India; drew taegeukgi/taegeuk lanterns for Mahabodhi Society Vesak in Kandy; re-examined by German scholar Zimmermann (2026); B4-band (1900-1945) record",
     srcs=["ibulgyo_lee_youngjae_2021","beopbo_lee_youngjae","kci_lee_youngjae_southasia","ibulgyo_zimmermann_2026","ibulgyo_doseokgi_2026"], date=D),

dict(id="P-0073", full="Hwang Su-yŏng", variants="Hwang Su-yeong; 黃壽永",
     hangul="황수영", hanja="黃壽永", indian=None,
     birth=None, birthp=None, death=None, deathp=None,
     nat="KOREAN", period="CONTEMPORARY",
     role="Art historian; professor at Dongguk University; pioneer of modern Korean field surveys of Indian Buddhist heritage",
     religion="Buddhist scholar (lay)",
     inst="Dongguk University",
     india="Surveyed India's Buddhist sites and ancient culture 1962-01-21 -> 1963-05-09 (~5 months): Ganges basin (Buddha's sites), Central, South and West India, and Pakistan (Peshawar area - trod the Ganuo-si temple site recorded in Hyecho's Wang ocheonchukguk jeon); itinerary arranged by the Indian government matched Hyecho's route; visited Nalanda; urged that Korea send students to India, regretting that Korean students were absent from the international students gathered at the Buddhist research institute near Nalanda",
     korea="Returned to Korea 1963-05-09 (Kyonghyang interview); compared Indian Buddhist remains with Korea's ancient culture (Korean stone pagodas); Indian officials requested a translation of Hyecho's travel record; his fieldwork was covered serially in Kyonghyang Shinmun",
     rel="DIRECT", travel="YES",
     tsum="Seoul -> India (Ganges basin; Central/South/West India; Pakistan-Peshawar); returned Seoul 1963-05-09",
     dir="KOREA_TO_INDIA", exch="INTELLECTUAL",
     evid="Kyonghyang Shinmun 1963-05-11 (帰国 interview, p.5); corroborated by Hyunbul News 2023-02-27 (Dongguk-Nalanda MOU feature)"
     ,
     sig="First documented modern Korean academic field survey of India's Buddhist heritage following Hyecho's route; precursor of Korea-India Buddhist-studies exchange",
     conf="HIGH", status="VERIFIED",
     notes="Lay scholar (not a monk); the 1962-63 journey predates ROK-India diplomatic relations (1973) and the documented Korean-student era in India; the institute near Nalanda where he noted absent Koreans is the precursor of Nav Nalanda Mahavihara; B5-band (post-war) record",
     srcs=["kyunghyang_hwang_1963","hyunbul_dongguk_nalanda"], date=D),

dict(id="P-0074", full="Muhak Chach'o", variants="Muhak Taesa; Muhak Daesa",
     hangul="무학 자초", hanja="無學 自超", indian=None,
     birth=1327, birthp=None, death=1405, deathp=None,
     nat="KOREAN", period="MEDIEVAL",
     role="Seon master; royal preceptor (왕사) of King T'aejo (Yi Sŏng-gye); abbot of Hoeamsa; third of the Jikong-Naong-Muhak line (삼대화상)",
     religion="Seon Buddhist monk",
     inst="Hoeamsa",
     india="No documented travel to India. India connection is indirect, through his teacher Jikong (Dhyānabhadra): per tradition he received Jikong's teaching (in Yuan China) before returning to Goryeo; he later co-led Hoeamsa, the temple Jikong founded (reportedly modeled on Nalanda), where Jikong's relics were enshrined (1370)",
     korea="With King T'aejo developed Hoeamsa as the leading early-Joseon temple; the Jikong-Naong-Muhak lineage formed the foundation of early Joseon Seon Buddhism; his stupa and stele were erected at Hoeamsa by order of King T'aejong",
     rel="INDIRECT", travel="NO",
     tsum="Goryeo -> Yuan China (per tradition, received Jikong's teaching) -> returned to Goryeo; no India travel documented",
     dir="INDIA_TO_KOREA", exch="RELIGIOUS",
     evid="Hyunbul News 2017-01-26 (Jikong's disciples incl. Muhak); Atlas News 2025-12-31 Silleuksa feature (삼대화상 선맥); Dongguk Buddhist Culture Portal (1370 relic stupa)",
     sig="Key carrier of the Indian master Jikong's lineage into Joseon Buddhism; with T'aejo he sustained the Nalanda-modeled Hoeamsa, the most prominent material legacy of Korea-India Buddhist contact in the late medieval era",
     conf="MEDIUM", status="VERIFIED",
     notes="India link entirely via Jikong tradition (Jahyeon 2017 monograph); no primary evidence of Muhak himself traveling to India; B2-band record; classified MEDIATOR/ADAPT",
     srcs=["hyunbul_jikong_2017","atlasnews_silleuksa_2025","buddhaland_hoeamsa_1370"], date=D),

dict(id="P-0075", full="Baegun Gyeonghan", variants="Baegun",
     hangul="백운 경한", hanja="白雲 景閑", indian=None,
     birth=1298, birthp=None, death=1374, deathp=None,
     nat="KOREAN", period="MEDIEVAL",
     role="Seon master; author of Jikjisimcheyojeol (1377) - the world's oldest extant book printed with movable metal type",
     religion="Seon Buddhist monk",
     inst="Chwiamsa (Cheongju)",
     india="No documented travel to India. India connection is indirect: per tradition he received inka (인가) from the Indian master Jikong (Dhyānabhadra) in Yuan China; his lineage transmission otherwise ran through Chinese masters (e.g. Shiwu Qinggong)",
     korea="Compiled the Jikjisimcheyojeol at Chwiamsa, Cheongju; a landmark of Korean Seon literature",
     rel="INDIRECT", travel="NO",
     tsum="Goryeo -> Yuan China (per tradition, received Jikong's inka) -> returned to Goryeo; no India travel documented",
     dir="INDIA_TO_KOREA", exch="RELIGIOUS;INTELLECTUAL",
     evid="Hyunbul News 2017-01-26 (Jikong's disciples incl. Baegun); Atlas News 2025-12-31 Silleuksa feature",
     sig="Demonstrates the reach of the Indian master Jikong's teaching among the most eminent Goryeo Seon masters of the Mongol period",
     conf="MEDIUM", status="VERIFIED",
     notes="India link entirely via Jikong tradition (Jahyeon 2017 monograph); Jikji fame is not itself India-connected; B2-band record; classified SECONDARY/ADAPT",
     srcs=["hyunbul_jikong_2017","atlasnews_silleuksa_2025"], date=D),

dict(id="P-0076", full="Sitanshu Yashaschandra", variants="Sitāṃśu Yaśaścandra; 시탄 슈 야사찬드라",
     hangul="시탄슈 야사찬드라", hanja=None, indian="સીતાંશુ યશશ્ચંદ્ર",
     birth=1941, birthp="YEAR", death=None, deathp="UNKNOWN",
     nat="INDIAN", period="CONTEMPORARY",
     role="Gujarati poet; scholar of Gujarati literature",
     religion="Hindu",
     inst="Saurashtra University (professor)",
     india="Gujarati poet described in the Dongguk newspaper as 'the youngest genius poet of India after Tagore'; visited Dongguk University (Seoul) and met Sŏ Chŏng-ju, discussing the mainstream and current state of Indian poetry; praised Sŏ's poem Hwasa (화사) for its compassion (자비심); proposed mutual Korean-Indian poetry translation and a '자비회' (Compassion Society) literary body, to be discussed with the Indian ambassador to Korea",
     korea="Documented Indian counterpart in Sŏ Chŏng-ju's literary encounter at Dongguk University",
     rel="DIRECT", travel="NO",
     tsum="India -> Korea: Dongguk University visit and meeting with Sŏ Chŏng-ju (year unstated)",
     dir="INDIA_TO_KOREA", exch="INTELLECTUAL",
     evid="Dongguk University newspaper (동대신문) interview article '[휴게실] 徐廷柱敎授, 印度詩人 야산챤드라 와' (reposted 2010-08-11)",
     sig="Documented Indian literary counterpart of Korea's foremost modern poet at a Buddhist university",
     conf="MEDIUM", status="VERIFIED",
     notes="Visit year not stated in the article (Sŏ was 문리대학장, likely 1970s); literary exchange, not Buddhist-institutional; B5-band record; classified SECONDARY/ADAPT",
     srcs=["donggukmedia_seo_yashaschandra"], date=D),

dict(id="P-0077", full="Ch'ukwŏn Chijŏn", variants="Ch'ukwŏn Chich'ŏn; Chukwon Jicheon; 竺源 智泉; National Preceptor Chŏngji (정지국사)",
     hangul="축원 지천", hanja="竺源 智泉", indian=None,
     birth=1324, birthp=None, death=1395, deathp=None,
     nat="KOREAN", period="MEDIEVAL",
     role="Goryeo Seon monk; disciple of the Indian master Jikong (Dhyānabhadra); titled National Preceptor Chŏngji (정지국사)",
     religion="Seon Buddhist monk",
     inst=None,
     india="No documented travel to India. India connection is indirect: per tradition he was one of Jikong's representative disciples (with Naong, Baegun Gyeonghan and Muhak Chach'o), receiving the Indian master's teaching in Yuan China",
     korea="Listed among Jikong's representative disciples in modern scholarship and temple tradition; the Jikong-Naong-Muhak lineage formed the foundation of early Joseon Seon Buddhism",
     rel="INDIRECT", travel="NO",
     tsum="Goryeo -> Yuan China (per tradition, disciple of Jikong) -> returned to Goryeo; no India travel documented",
     dir="INDIA_TO_KOREA", exch="RELIGIOUS",
     evid="Hyunbul News 2017-01-26 (Jikong's disciples incl. Ch'ukwŏn); Atlas News 2025-12-31 Silleuksa feature (정지국사 축원지천, 1324-1395)",
     sig="Completes the documented circle of the Indian master Jikong's Korean disciples in the late Goryeo period",
     conf="MEDIUM", status="VERIFIED",
     notes="India link entirely via Jikong tradition (Jahyeon 2017 monograph); details of his career beyond the title 정지국사 not documented in the sources consulted; B2-band record; classified SECONDARY/ADAPT",
     srcs=["hyunbul_jikong_2017","atlasnews_silleuksa_2025"], date=D),
]
