# -*- coding: utf-8 -*-
"""People data module 2/9: P-0009..P-0017 (ancient/medieval). Compiled 2026-08-16 from verified web research."""
D = "2026-08-16"

PEOPLE_2 = [
dict(id="P-0009", full="Iryŏn", variants="Il-yeon; Ilyon; Ichinen (Japanese); 一然; born Kim Gyeon-myeong",
     hangul="일연", hanja="一然", indian=None,
     birth=1206, birthp="YEAR", death=1289, deathp="YEAR",
     nat="KOREAN (Goryeo)", period="MEDIEVAL",
     role="Buddhist monk; historian; author",
     religion="Buddhism (Seon)",
     inst="Inheungsa; Unmunsa; posthumous title Bogak Guksa",
     india="Compiled the Samguk Yusa (三國遺事, c. 1283-1287), the primary medieval Korean source preserving the Marananta, Gyeomik, Heo Hwang-ok and Suro traditions about Indian contact",
     korea="Goryeo monk; author of Korea's most important historical compendium after Kim Busik's Samguk Sagi",
     rel="MEDIATED", travel="NO", tsum="NULL",
     dir="INDIA_TO_KOREA", exch="RELIGIOUS;LITERARY;INTELLECTUAL",
     evid="Samguk Yusa is the source for most legendary India-Korea traditions studied today",
     sig="Sole compiler of many early India-Korea narratives; critical for the Marananta/Heo Hwang-ok/Suro historiography",
     conf="HIGH", status="VERIFIED",
     notes="Wrote ~80 volumes; only Samguk Yusa survives.",
     srcs=["loc_iryon","wiki_ilyeon"], date=D),

dict(id="P-0010", full="Hyeil (Silla esoteric monk)", variants="惠日; C. Huiri",
     hangul="혜일", hanja="惠日", indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="KOREAN (Silla)", period="ANCIENT",
     role="Buddhist monk; Esoteric (Milgyo) master",
     religion="Buddhism (Esoteric/Vajrayana); disciple of Amoghavajra (705-774)",
     inst="Tang (Chang'an) milieu; 'Six Disciples of Amoghavajra' orbit",
     india="Inherited Indian-origin esoteric teaching of Amoghavajra; introduced to Silla the Buddha-Usnisa Dharani tradition",
     korea="Carried Amoghavajra-lineage Vajrayana back to Silla (King Wonseong era, c. 789)",
     rel="INDIRECT", travel="NO",
     tsum="NULL (Silla->Tang->Silla; no India travel recorded)",
     dir="INDIA_TO_KOREA", exch="RELIGIOUS",
     evid="KCI scholarship traces Goryeo Buddha-Usnisa practice halls to the Bukong->Hyeil lineage; EncyKorea '밀교' lists Silla 惠日 among esoteric monks",
     sig="Key conduit of Indian-origin esoteric Buddhism to late Silla",
     conf="MEDIUM", status="VERIFIED",
     notes="DO NOT confuse with (a) Goryeo Hwaeom monk Gyeoleung (courtesy name 慧日), (b) late-Goryeo Jeju poet-monk 慧日, or (c) a Japanese monk 惠日 (623).",
     srcs=["kci_kimsooyeon","encykorea_milgyo"], date=D),

dict(id="P-0011", full="Gyeomik", variants="Kyŏmik; Gyomik; 謙益",
     hangul="겸익", hanja="謙益", indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="KOREAN (Baekje)", period="ANCIENT",
     role="Monk; Vinaya (Lu) scholar-translator",
     religion="Buddhism (Vinaya)",
     inst="Sangana Great Vinaya Monastery (常伽那大律寺), Central India; Heungnyunsa (Baekje)",
     india="Travelled to India by sea in 526 (Seongwang 4); studied Sanskrit 5 years at Sangana; returned 531 with Indian monk Baedalta bearing Sanskrit Abhidharma and Five-Part Vinaya texts",
     korea="Translated 72 volumes of Vinaya with 28 monks; founded the Baekje Vinaya school",
     rel="DIRECT", travel="YES",
     tsum="Sea route out (526) -> Central India (Sangana, 5 years) -> return 531 via sea with Indian Vinaya master Baedalta",
     dir="INDIA_TO_KOREA", exch="RELIGIOUS;LINGUISTIC;INTELLECTUAL",
     evid="Recorded in Korean tradition (Samguk Yusa and later compilations); encyclopedia entries on the Baekje Vinaya school",
     sig="Baekje's greatest documented Indian pilgrim; brought Vinaya and Sanskrit scholarship to Korea",
     conf="MEDIUM", status="PARTIAL",
     notes="Recorded in Korean Buddhist tradition; surviving sources are later compilations.",
     srcs=["encyclopedia_kyomik","wiki_kyeomik"], date=D),

dict(id="P-0012", full="Baedalta", variants="倍達多 (modern Sanskrit reconstruction not attested)",
     hangul=None, hanja="倍達多", indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="INDIAN", period="ANCIENT",
     role="Indian Tripitaka master (三藏)",
     religion="Buddhism",
     inst="(travelled with Gyeomik)",
     india="Indian monk who accompanied Gyeomik to Baekje in 531, carrying Sanskrit Abhidharma and Vinaya texts",
     korea="His arrival in Baekje (531) supported the establishment of the Vinaya school",
     rel="DIRECT", travel="YES",
     tsum="India -> Baekje by sea, 531 CE (with Gyeomik)",
     dir="INDIA_TO_KOREA", exch="RELIGIOUS",
     evid="Korean Buddhist tradition (via Gyeomik narrative); encyclopedia entries on Baekje Vinaya",
     sig="Attested Indian monk physically present in Korea; rare documented 6th-century India-to-Korea movement",
     conf="MEDIUM", status="PARTIAL",
     notes="Hanja given in tradition; do not assert a specific Sanskrit reconstruction.",
     srcs=["encyclopedia_kyomik","wiki_kyeomik"], date=D),

dict(id="P-0013", full="Ariyabalma", variants="阿離耶跋摩",
     hangul=None, hanja="阿離耶跋摩", indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="KOREAN (Silla)", period="ANCIENT",
     role="Pilgrim monk",
     religion="Buddhism",
     inst="Nalanda Mahavihara",
     india="From Chang'an went to India, stayed at Nalanda, studied sutras and died there aged 70+",
     korea="Recorded in Yijing's Da Tang Xiyu qiufa gaoseng zhuan (大唐西域求法高僧傳) as a Silla person (新罗人)",
     rel="DIRECT", travel="YES",
     tsum="Silla -> Chang'an -> Nalanda (Central India); died at Nalanda",
     dir="KOREA_TO_INDIA", exch="RELIGIOUS;INTELLECTUAL",
     evid="Yijing's 7th-century record (contemporary witness); modern Korean scholarship (KCI)",
     sig="Contemporary 7th-century testimony of a Silla monk resident at Nalanda",
     conf="MEDIUM", status="VERIFIED",
     notes="Recorded by Yijing (義淨), who visited India 671-695.",
     srcs=["yijing_wikisource","historylibrary_silla"], date=D),

dict(id="P-0014", full="Hyeeop", variants="Hyŏp; 慧業",
     hangul="혜업", hanja="慧業", indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="KOREAN (Silla)", period="ANCIENT",
     role="Pilgrim monk",
     religion="Buddhism",
     inst="Bodhi temple (Bodhgaya); Nalanda",
     india="Travelled to India, dwelt at Bodhi temple (Bodhgaya) and Nalanda; died there aged ~60; his Sanskrit manuscripts were seen at Nalanda by Yijing's party",
     korea="Silla monk; noted in a colophon as '新罗僧慧业写记' at the Buddha-tooth tree",
     rel="DIRECT", travel="YES",
     tsum="Silla -> India (Bodhgaya, Nalanda); died in India",
     dir="KOREA_TO_INDIA", exch="RELIGIOUS;INTELLECTUAL",
     evid="Yijing's Da Tang Xiyu qiufa gaoseng zhuan",
     sig="Physical presence of a Silla monk at Bodhgaya/Nalanda attested in Yijing's record",
     conf="MEDIUM", status="VERIFIED", notes="NULL",
     srcs=["yijing_wikisource","historylibrary_silla"], date=D),

dict(id="P-0015", full="Hyŏnt'ae", variants="賢泰",
     hangul="현태", hanja="賢泰", indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="KOREAN (Silla)", period="ANCIENT",
     role="Pilgrim monk",
     religion="Buddhism",
     india="Travelled to India; returned to Tang; died in China",
     korea="Silla monk recorded among the Silla contingent in Yijing's compilation",
     rel="DIRECT", travel="YES",
     tsum="Silla -> India -> Tang (died in China)",
     dir="KOREA_TO_INDIA", exch="RELIGIOUS",
     evid="Yijing's Da Tang Xiyu qiufa gaoseng zhuan",
     sig="Part of the documented 7th-century Silla cohort at Indian Buddhist sites",
     conf="MEDIUM", status="VERIFIED", notes="NULL",
     srcs=["yijing_wikisource","historylibrary_silla"], date=D),

dict(id="P-0016", full="Hyŏngak", variants="玄恪",
     hangul="현각", hanja="玄恪", indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="KOREAN (Silla)", period="ANCIENT",
     role="Pilgrim monk",
     religion="Buddhism",
     india="Accompanied Chinese monk Xuanzhao (玄照) in the Zhenguan era to Dajue Temple (Bodhgaya); died sick there in his 40s",
     korea="Silla monk recorded in Yijing's compilation",
     rel="DIRECT", travel="YES",
     tsum="Silla -> India (with Xuanzhao) -> died at Bodhgaya",
     dir="KOREA_TO_INDIA", exch="RELIGIOUS",
     evid="Yijing's Da Tang Xiyu qiufa gaoseng zhuan",
     sig="Documented Silla monk who died at Bodhgaya in the 7th century",
     conf="MEDIUM", status="VERIFIED", notes="NULL",
     srcs=["yijing_wikisource","historylibrary_silla"], date=D),

dict(id="P-0017", full="Gubon", variants="求本",
     hangul="구본", hanja="求本", indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="KOREAN (Silla)", period="ANCIENT",
     role="Pilgrim monk",
     religion="Buddhism",
     india="Went to India (recorded with the Silla contingent in Yijing)",
     korea="Silla monk recorded in Yijing's compilation",
     rel="DIRECT", travel="YES",
     tsum="Silla -> India",
     dir="KOREA_TO_INDIA", exch="RELIGIOUS",
     evid="Yijing's Da Tang Xiyu qiufa gaoseng zhuan",
     sig="Part of the documented 7th-century Silla cohort in India",
     conf="MEDIUM", status="VERIFIED", notes="NULL",
     srcs=["yijing_wikisource","historylibrary_silla"], date=D),
]
