# -*- coding: utf-8 -*-
"""People data module 5/9: P-0038..P-0050 (20th-century political/diplomatic/military/economic). Compiled 2026-08-16."""
D = "2026-08-16"

PEOPLE_5 = [
dict(id="P-0038", full="Mohandas Karamchand Gandhi", variants="Mahatma Gandhi; Gandhiji",
     hangul=None, hanja=None, indian="मोहनदास करमचंद गांधी",
     birth=1869, birthp="DAY", death=1948, deathp="DAY",
     nat="INDIAN", period="MODERN",
     role="Lawyer; political and spiritual leader of the Indian independence movement",
     religion="Hindu (Vaishnava with Jain influences); secularist in politics",
     inst="Indian National Congress",
     india="Central figure of the Indian independence movement",
     korea="MEDIATED influence: Korean press under Japanese rule reported his Non-Cooperation Movement, influencing Korea's own independence movement; Korean thinker-activist Ham Sok-hon (1901-1989), 'the Korean Gandhi', was directly influenced by his philosophy; later influence on Korean democracy movements",
     rel="INDIRECT", travel="NO",
     tsum="Never visited Korea (died 1948)",
     dir="INDIA_TO_KOREA", exch="POLITICAL;INTELLECTUAL",
     evid="Indian Express (15 Aug 2021) on Gandhi's influence on Korea's freedom struggle; mkgandhi.org on Ham Sok-hon",
     sig="His nonviolence doctrine became a model for Korea's independence and later democracy movements",
     conf="MEDIUM", status="VERIFIED",
     notes="Include only as an influence figure - no documented direct Gandhi-Korea writing, visit, or contact found.",
     srcs=["indianexpress_gandhi","mkgandhi_ham"], date=D),

dict(id="P-0039", full="Jawaharlal Nehru", variants="Pandit Nehru",
     hangul=None, hanja=None, indian="जवाहरलाल नेहरू",
     birth=1889, birthp="DAY", death=1964, deathp="DAY",
     nat="INDIAN", period="CONTEMPORARY",
     role="Prime Minister of India (1947-1964); statesman; architect of India's Korea policy",
     religion="Agnostic (self-described); secularist",
     inst="Government of India; Indian National Congress",
     india="Prime Minister of India 1947-1964",
     korea="With V.K. Krishna Menon, sponsored the UN resolution on Korean POW settlement; India chaired the resulting Neutral Nations Repatriation Commission (NNRC); proposal initially rejected by China/DPRK on 3 Dec 1952; Nehru Archive preserves Korea cables (4 Mar & 25 May 1953)",
     rel="INDIRECT", travel="NO",
     tsum="Korea absent from his official list of 35 international trips (43 countries); no record of any Korea visit",
     dir="INDIA_TO_KOREA", exch="DIPLOMATIC;POLITICAL;MILITARY",
     evid="UN adopted the Indian resolution; NNRC created with Indian chairman (Thimayya) and Indian Custodian Force; Nehru Archive cables",
     sig="India's mediation was pivotal to the POW-repatriation settlement ending the Korean War's humanitarian crisis",
     conf="HIGH", status="VERIFIED",
     notes="Korea policy role fully documented; non-visit inferred from absence in official trip list.",
     srcs=["nehruarchive_korea","nyt_nehru","wiki_nehru_trips"], date=D),

dict(id="P-0040", full="Vengalil Krishnan Krishna Menon", variants="V.K. Krishna Menon; Krishna Menon",
     hangul=None, hanja=None, indian=None,
     birth=1896, birthp="DAY", death=1974, deathp="DAY",
     nat="INDIAN", period="CONTEMPORARY",
     role="Diplomat; barrister; India's chief delegate to UN during Korean armistice debates; Minister of Defence",
     religion="Agnostic",
     inst="Government of India; United Nations",
     india="India's permanent representative to the UN; Defence Minister",
     korea="Led India's UNGA campaign for POW settlement; UNGA Korea debate ended 7 March 1953 with India's resolution rejected by Communist powers; Churchill welcomed revised proposals aligned with the Indian Resolution (25 May 1953 cable)",
     rel="INDIRECT", travel="UNCERTAIN",
     tsum="No evidence of travel to Korea; operated from UN, New York",
     dir="INDIA_TO_KOREA", exch="DIPLOMATIC;POLITICAL",
     evid="Nehru Archive cables (4 Mar 1953; 25 May 1953); UNGA 1953 debate record",
     sig="Principal Indian negotiator behind the UN's Korean armistice/POW diplomacy of 1952-53",
     conf="HIGH", status="VERIFIED",
     notes="Travel to Korea unverified and unlikely; role fully verified.",
     srcs=["nehruarchive_cable1","nehruarchive_cable2","worldlii_unga","nehruarchive_km"], date=D),

dict(id="P-0041", full="Kavalam Madhava Panikkar", variants="K.M. Panikkar; Sardar K.M. Panikkar",
     hangul=None, hanja=None, indian=None,
     birth=1895, birthp="DAY", death=1963, deathp="DAY",
     nat="INDIAN", period="CONTEMPORARY",
     role="Historian; diplomat; India's first ambassador to the People's Republic of China (1950-52); later ambassador to Egypt and France",
     religion="NULL",
     inst="Government of India (IFS); UN",
     india="India's ambassador to China during the Korean War",
     korea="Acted as the communication bridge between Beijing and the West during the Korean War; relayed Zhou Enlai's 3 Oct 1950 warning (China would enter Korea if UN forces crossed the 38th parallel) to the US",
     rel="INDIRECT", travel="NO",
     tsum="Korea visit unverified; role exercised from Beijing embassy",
     dir="INDIA_TO_KOREA", exch="DIPLOMATIC;POLITICAL",
     evid="DVIDS/US Army Intelligence history (Panikkar as go-between, 25 Sep & 3 Oct 1950); MP-IDSA commentary (2025); Nehru Archive cables (19 Aug, 22 Dec 1950)",
     sig="His channel helped the West read China's intervention intent in the Korean War",
     conf="HIGH", status="VERIFIED",
     notes="No evidence he ever set foot in Korea.",
     srcs=["dvidshub_panikkar","idsa_panikkar","wiki_panikkar","nehruarchive_panikkar"], date=D),

dict(id="P-0042", full="Kumara Padmanabha Sivasankara Menon", variants="K.P.S. Menon; K.P.S. Menon (senior)",
     hangul=None, hanja=None, indian=None,
     birth=1898, birthp="DAY", death=1982, deathp="DAY",
     nat="INDIAN", period="CONTEMPORARY",
     role="ICS officer; diplomat; India's first Foreign Secretary (1948-52); ambassador to USSR (1952-61); Chairman, UN Temporary Commission on Korea (UNTCOK, 1947-48)",
     religion="NULL",
     inst="Government of India; United Nations",
     india="First Foreign Secretary of independent India",
     korea="UN-appointed Chairman of UNTCOK (1947-48); supervised the first general elections in South Korea that led to the founding of the Republic of Korea (15 Aug 1948)",
     rel="DIRECT", travel="YES",
     tsum="In Korea as UNTCOK chairman 1947-48; NYT (6 Mar 1948): returned to Seoul for commission sessions; statements at the UN Interim Committee on Korea (19 Feb 1948)",
     dir="INDIA_TO_KOREA", exch="DIPLOMATIC;POLITICAL",
     evid="Embassy of India Seoul history page; UN Digital Library statement record; NYT 1948; MG University bio",
     sig="Headed the UN body whose elections established the Republic of Korea",
     conf="HIGH", status="VERIFIED",
     notes="Chaired UNTCOK (1947-48), not the later UNCOK (1948-50); Wikipedia's 'UNCOK 1948' phrasing is imprecise.",
     srcs=["nyt_kpsmenon","un_kpsmenon","embassy_india","mgu_kps"], date=D),

dict(id="P-0043", full="Kodandera Subayya Thimayya", variants="K.S. Thimayya; General K.S. Thimayya",
     hangul=None, hanja=None, indian=None,
     birth=1906, birthp="DAY", death=1965, deathp="DAY",
     nat="INDIAN", period="CONTEMPORARY",
     role="Indian Army officer; Chairman, Neutral Nations Repatriation Commission (NNRC) 1953-54; later Chief of the Army Staff (1957-61)",
     religion="NULL",
     inst="Indian Army; NNRC (UN)",
     india="Career Indian Army officer; COAS 1957-61",
     korea="NNRC Chairman; arrived Korea 27 July 1953 (armistice day); led India's neutral supervision of POW repatriation with Sweden, Switzerland, Poland, Czechoslovakia; memorialized with a bust at Imjingak Peace Park (unveiled 2026)",
     rel="DIRECT", travel="YES",
     tsum="Stationed in Korea 1953-54 as NNRC Chairman",
     dir="INDIA_TO_KOREA", exch="MILITARY;DIPLOMATIC;HUMANITARIAN",
     evid="Korean Medals NNRC history; Korea Herald memorial coverage; Embassy of India Seoul page",
     sig="Chaired the commission that resolved the Korean War's POW impasse - India's most visible 20th-century peacekeeping role",
     conf="HIGH", status="VERIFIED",
     notes="Alternate NNRC Chairman was Indian ambassador B.N. Chakravarty.",
     srcs=["koreanmedals_nnrc","koreaherald_thimayya","embassy_india","wiki_thimayya"], date=D),

dict(id="P-0044", full="S. P. P. Thorat", variants="Shankarrao Pandurang Patil Thorat; Lt. Gen. S.P.P. Thorat",
     hangul=None, hanja=None, indian=None,
     birth=1906, birthp="DAY", death=1992, deathp="DAY",
     nat="INDIAN", period="CONTEMPORARY",
     role="Indian Army officer (Lieutenant General); Commander, Custodian Force of India (ICF) in Korea; later GOC-in-C Eastern Command",
     religion="NULL",
     inst="Indian Army; NNRC (ICF)",
     india="Senior Indian Army officer",
     korea="Commanded the Custodian Force (India) in Korea 1953-54; supervised neutral custody and repatriation of 22,000+ POWs; decorated with Kirti Chakra and Padma Shri",
     rel="DIRECT", travel="YES",
     tsum="Served in Korea 1953-54 commanding ICF operations under the NNRC",
     dir="INDIA_TO_KOREA", exch="MILITARY;DIPLOMATIC;HUMANITARIAN",
     evid="Official history 'History of the Custodian Force (India) in Korea, 1953-54' (published); Korean Medals ICF records; Nehru Archive profile; en-wiki",
     sig="Led India's largest overseas military deployment before the 1960s (Congo); the ICF mission is India's first foreign peacekeeping operation",
     conf="HIGH", status="VERIFIED",
     notes="Full name Shankarrao Pandurang Patil Thorat confirmed (Nehru Archive profile; en-wiki); b. 12 Aug 1906, d. 10 Aug 1992; GOC-in-C Eastern Command in the lead-up to the 1962 Sino-Indian War (not Southern Command).",
     srcs=["googlebooks_icf","koreanmedals_icf","nehruarchive_thorat","wiki_spp_thorat"], date=D),

dict(id="P-0045", full="B. N. Chakravarty", variants="B.N. Chakravarty",
     hangul=None, hanja=None, indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="INDIAN", period="CONTEMPORARY",
     role="Indian ambassador; Alternate Chairman of the NNRC (1953-54)",
     religion="NULL",
     inst="Government of India; NNRC",
     india="Indian diplomat",
     korea="Served in Korea as Alternate Chairman of the NNRC during the POW repatriation operation 1953-54",
     rel="DIRECT", travel="YES",
     tsum="In Korea 1953-54 with the NNRC",
     dir="INDIA_TO_KOREA", exch="DIPLOMATIC;MILITARY",
     evid="Korean Medals NNRC history; Embassy of India Seoul page (via Thimayya entry)",
     sig="Senior Indian diplomat on the NNRC during the Korean War settlement",
     conf="MEDIUM", status="PARTIAL",
     notes="Biographical details sparse in accessible sources; verify against NNRC official records. Possible identification with Binay Ranjan Sen is NOT confirmed - do not conflate.",
     srcs=["koreanmedals_nnrc","embassy_india"], date=D),

dict(id="P-0046", full="A. G. Rangaraj", variants="Lt. Col. A.G. Rangaraj",
     hangul=None, hanja=None, indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="INDIAN", period="CONTEMPORARY",
     role="Indian Army officer (Lieutenant Colonel); commanded the 60th Indian Parachute Field Ambulance",
     religion="NULL",
     inst="Indian Army; 60th Indian Parachute Field Ambulance (UN)",
     india="Indian Army officer; India's first military paratrooper",
     korea="Commanded the 60th Indian Parachute Field Ambulance which arrived at Busan 20 Nov 1950 under the UN flag; unit served in the Korean War medical mission; honored at the Imjingak memorial",
     rel="DIRECT", travel="YES",
     tsum="Arrived Busan, Korea 20 Nov 1950; unit served in Korea during the war",
     dir="INDIA_TO_KOREA", exch="MILITARY;HUMANITARIAN",
     evid="Korean Medals 60th Indian Parachute Field Ambulance page; Imjingak memorial",
     sig="Led India's first military unit in Korea (medical mission, 1950)",
     conf="MEDIUM", status="PARTIAL",
     notes="Unit-level records verified; personal biographical details sparse.",
     srcs=["koreanmedals_60pfa"], date=D),

dict(id="P-0047", full="Syed Muzaffar Aga", variants="Muzaffar Aga",
     hangul=None, hanja=None, indian=None,
     birth=1919, birthp="APPROX", death=2026, deathp="YEAR",
     nat="INDIAN", period="CONTEMPORARY",
     role="Civil servant; diplomat; India's FIRST ambassador to the Republic of Korea (Dec 1974 - Oct 1977)",
     religion="NULL",
     inst="Government of India (IFS); Embassy of India, Seoul",
     india="Former Jammu & Kashmir IAS officer (first Transport Commissioner, Financial Commissioner); later Chief Secretary of J&K (1978-80)",
     korea="First Indian ambassador to the Republic of Korea after diplomatic relations were established (1973); served in Seoul Dec 1974 - Oct 1977",
     rel="DIRECT", travel="YES",
     tsum="Served in Seoul, Korea 1974-1977",
     dir="INDIA_TO_KOREA", exch="DIPLOMATIC;POLITICAL",
     evid="Kashmir Life obituary (2026); Wikipedia list of Indian ambassadors to South Korea",
     sig="Founding figure of India's resident diplomatic presence in South Korea",
     conf="MEDIUM", status="VERIFIED",
      notes="Died July 2026 at age 108 per Kashmir Life obituary (which gives Seoul tenure 1975-78); Wikipedia ambassador list records Dec 1974 - Oct 1977 - minor discrepancy, dates unadjudicated.",
     srcs=["kashmirlife_aga","wiki_india_ambassadors"], date=D),

dict(id="P-0048", full="Park Chan-hyun", variants="박찬현",
     hangul="박찬현", hanja=None, indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="KOREAN (South Korea)", period="CONTEMPORARY",
     role="Diplomat; politician; FIRST ROK ambassador to India (Feb 1974 - June 1976)",
     religion="NULL",
     inst="Ministry of Foreign Affairs (ROK); Embassy of the Republic of Korea, New Delhi",
     india="First South Korean ambassador to India; embassy upgraded from the 1962 New Delhi consulate after the 10 Dec 1973 recognition of the Republic of Korea",
     korea="Later served as National Assembly member",
     rel="DIRECT", travel="YES",
     tsum="Served in New Delhi, India 1974-1976",
     dir="KOREA_TO_INDIA", exch="DIPLOMATIC;POLITICAL",
     evid="NamuWiki entry on Park Chan-hyun; ROK embassy history page",
     sig="Founding figure of South Korea's resident diplomatic presence in India",
     conf="MEDIUM", status="VERIFIED",
     notes="Korean-language source (NamuWiki); corroborate with MOFA records in next phase.",
     srcs=["namuwiki_park","namuwiki_embassy"], date=D),

dict(id="P-0049", full="Kim Woo-choong", variants="Kim Woo-Choong; Gim Ujung; Kim Woo-jung",
     hangul="김우중", hanja="金宇中", indian=None,
     birth=1936, birthp="DAY", death=2019, deathp="DAY",
     nat="KOREAN (South Korea)", period="CONTEMPORARY",
     role="Businessman; founder and chairman of the Daewoo Group until its 1999 collapse",
     religion="NULL",
     inst="Daewoo Group; DCM-Daewoo joint venture",
     india="Led Daewoo's entry into India via the DCM-Daewoo joint venture; in New Delhi on 7 June 1994 at the launch of the Racer with DCM Chairman S.G. Awasthi; Daewoo Cielo assembly (India JV 1995, initial capacity 50,000 units/yr)",
     korea="Chairman of Korea's second-largest chaebol; global expansion into India, Uzbekistan, Poland, Vietnam",
     rel="DIRECT", travel="YES",
     tsum="Physically present in New Delhi, 7 June 1994, for the DCM-Daewoo Racer launch",
     dir="KOREA_TO_INDIA", exch="ECONOMIC",
     evid="Times of India photo archive (June 1994); Daewoo Motors India operations; automotive press coverage",
     sig="First major Korean auto investment in India post-liberalization; helped open the Indian market to Korean chaebols",
     conf="HIGH", status="VERIFIED",
     notes="Personal travel verified via the TOI photo archive; company-level India operations corroborated by Daewoo Motors history.",
     srcs=["toi_kimwoochoong","wiki_kwc","britannica_kwc"], date=D),

dict(id="P-0050", full="Lee Kun-hee", variants="Lee Kun-Hee",
     hangul="이건희", hanja="李健熙", indian=None,
     birth=1942, birthp="DAY", death=2020, deathp="DAY",
     nat="KOREAN (South Korea)", period="CONTEMPORARY",
     role="Businessman; chairman of Samsung Group and Samsung Electronics (1987-2008, 2010-2020)",
     religion="NULL",
     inst="Samsung Group",
     india="Under his leadership Samsung entered India: Samsung India Electronics Pvt. Ltd. incorporated 3 August 1995 (MCA CIN U31900DL1995PTC071387), operations from December 1995 - the seed of today's Noida mega-factory",
     korea="Chairman of Korea's largest chaebol; 'New Management' globalization drive 1993 onward included India",
     rel="INDIRECT", travel="UNCERTAIN",
     tsum="NULL - company presence verified; personal travel unverified",
     dir="KOREA_TO_INDIA", exch="ECONOMIC",
     evid="MCA incorporation record (3 Aug 1995); Samsung's own history (operations began Dec 1995); subsequent world's-largest mobile plant at Noida",
     sig="His globalization strategy established Samsung's India manufacturing base - among the largest Korean investments in India",
     conf="MEDIUM", status="PARTIAL",
     notes="Corporate India connection VERIFIED; personal visit UNVERIFIED (physically_traveled = UNCERTAIN).",
     srcs=["companycheck_samsung","britannica_lee","wiki_lee"], date=D),
]
