# -*- coding: utf-8 -*-
"""People data module 1/9: P-0001..P-0008 (ancient/medieval). Compiled 2026-08-16 from verified web research (see docs/methodology.md). source_ids reference keys in data_sources.py."""
D = "2026-08-16"

PEOPLE_1 = [
dict(id="P-0001", full="Hyecho", variants="Hye-ch'o; Huichao; Hye Ch'o; 慧超; 惠超",
     hangul="혜초", hanja="慧超", indian=None,
      birth=704, birthp="APPROX", death=787, deathp="APPROX",
     nat="KOREAN (Silla)", period="ANCIENT",
     role="Buddhist monk; pilgrim; translator",
     religion="Buddhism (Esoteric/Vajrayana; disciple of Vajrabodhi and Amoghavajra)",
     inst="Juefu Temple (Chang'an); Dryuan Puti Temple (Mt Wutai)",
     india="Pilgrimage to the Five Indias c. 723-727 (sea out via Guangzhou, land back via Central Asia/Persia); visited Kushinagara, Varanasi, Rajagrha, Bodhgaya, Lumbini, Kashmir, Gandhara",
     korea="Silla-born; never returned to Korea; active in Tang; among Amoghavajra's six great disciples; later in Japanese Shingon lineage",
     rel="DIRECT", travel="YES",
     tsum="Departed Guangzhou by sea (c. 719 or 723); toured the Five Indias; reached Nishapur (Persia); returned overland via Pamir/Central Asia; account ends at Kucha, Nov 727",
     dir="BIDIRECTIONAL", exch="RELIGIOUS;LITERARY;INTELLECTUAL",
     evid="Wang ocheonchukguk jeon (往五天竺國傳), the sole surviving 8th-c. East Asian record of India/Central Asia; Dunhuang ms. (Pelliot 1908), Bibliothèque nationale de France",
     sig="First Korean recorded to have travelled to India by sea and returned overland leaving a written record; 'world's oldest of the four great travelogues' per Korean scholarship",
     conf="HIGH", status="VERIFIED",
      notes="Travel dates conflict across sources (719-727 vs 723-727/728; '730경' per our-history-net). Standard Korean dates 704-787 (Korean Wikipedia, NIKH-adjacent sources, 인천in); birth c. 700 / death 780 appear in older scholarship - kept as variant. Author identification with Amoghavajra's Silla disciple is scholarly consensus (Takakusu).",
      srcs=["encykorea_wangoj","encykorea_hyecho","nih_hyecho","kci_hyecho","kiss_hyecho","ko_wiki_hyecho"], date=D),

dict(id="P-0002", full="Woncheuk", variants="Wŏnch'ŭk; Wonchuk; Wuan-tshe (Tibetan); Ximing dashi; 圓測",
     hangul="원측", hanja="圓測", indian=None,
     birth=613, birthp="YEAR", death=696, deathp="YEAR",
     nat="KOREAN (Silla)", period="ANCIENT",
     role="Buddhist monk; Yogacara scholar; abbot",
     religion="Buddhism (East Asian Yogacara/Cittamatra)",
     inst="Ximing Monastery (西明寺), Chang'an",
     india="Studied Indian Yogacara doctrine (Vasubandhu's texts) via Xuanzang's translations in Chang'an; never travelled to India",
     korea="Silla royal family (grandson of King Chinp'yong per some accounts); ordained at 15 in Silla before going to Tang",
     rel="INDIRECT", travel="NO",
     tsum="NULL (Silla->Tang c. 627 only; lived in Chang'an)",
     dir="INDIA_TO_KOREA", exch="RELIGIOUS;INTELLECTUAL",
     evid="Commentaries (e.g., on Samdhinirmocana-sutra) studied and quoted in Tibetan doxographies; long-standing rivalry with Kuiji",
     sig="One of the most influential Silla monks in Tang China; his works transmitted to Tibet",
     conf="HIGH", status="VERIFIED",
     notes="Dates 613-696 per John Powers (JIABS); some accounts differ slightly.",
     srcs=["powers_jiabs","eob_woncheuk"], date=D),

dict(id="P-0003", full="Wŏnhyo", variants="Wonhyo; Wŏn-hyo; 元曉; Haedong bosal; 'Jinna bosal' epithet in China",
     hangul="원효", hanja="元曉", indian=None,
     birth=617, birthp="YEAR", death=686, deathp="YEAR",
     nat="KOREAN (Silla)", period="ANCIENT",
     role="Buddhist philosopher-monk; author; popularizer; founder of Haedongjong",
     religion="Buddhism (Hwaeom/Huayan and broader Mahayana)",
     inst="Hwangnyongsa milieu; Haedongjong lineage",
     india="Deeply studied Indian-origin texts, esp. the Awakening of Faith (attributed to Asvaghosa); wrote famous Haedong-so commentaries; legend of an aborted trip to Tang/India",
     korea="Silla native; tutored many Silla monks; works transmitted to Tang and Japan",
     rel="INDIRECT", travel="NO",
     tsum="Legend (hagiography): while travelling to Tang with Ŭisang, awakened overnight in a cave ('mind only') and never went abroad; no India journey recorded",
     dir="INDIA_TO_KOREA", exch="RELIGIOUS;INTELLECTUAL",
     evid="Haedong-so commentaries studied in Tang/Japan; called 'Jinna bosal' in China (equated with Indian logician Dignaga); T'ong pulgyo synthesis",
     sig="Korea's greatest Buddhist philosopher; synthesized Indian/Chinese Buddhist thought for Korea",
     conf="HIGH", status="VERIFIED",
     notes="Person and works verified; the cave legend is traditional hagiography. Relationship to India is intellectual, not physical.",
     srcs=["acmuller_wonhyo","encykorea_wonhyo","encykorea_haedongjong"], date=D),

dict(id="P-0004", full="Kyŏnghŭng", variants="Gyeongheung; 憬興; Su Kyŏnghŭng",
     hangul="경흥", hanja="憬興", indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="KOREAN (Silla; born Ungcheon, former Baekje territory)", period="ANCIENT",
     role="Buddhist monk; commentator; one of Silla's 'Three/Four Great Writers'",
     religion="Buddhism (specialized in Pure Land/Amitabha commentary)",
     inst="Samrangsa (三郎寺); made Kukro (national elder) by King Sinmun",
     india="Authored commentaries on Indian-derived sutras (Three Pure Land sutras incl. the Smaller Sukhavativyuha; Golden Light Sutra) without travelling to India",
     korea="Silla monk under King Sinmun (r. 681-692); works survive via Japanese holdings",
     rel="INDIRECT", travel="NO", tsum="NULL",
     dir="INDIA_TO_KOREA", exch="RELIGIOUS;INTELLECTUAL",
     evid="Sam Mireukgyeong so (三彌勒經疏) and Muryangsugyong yonuisulmunchan survive; the latter long studied in Japan; ~40 works recorded, 3 extant",
     sig="Major Silla exegete of Indian Buddhist scriptural heritage; bridge from Baekje-refugee traditions into Unified Silla scholarship",
     conf="MEDIUM", status="VERIFIED",
     notes="Exact dates unrecorded; ordained at 18; lived during King Sinmun's reign.",
     srcs=["encykorea_gyeongheung","ucla_kyeongheung"], date=D),

dict(id="P-0005", full="T'aehyŏn", variants="Taehyon; Tae-hyŏn; 太賢; 大賢",
     hangul="태현", hanja="太賢", indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="KOREAN (Silla)", period="ANCIENT",
     role="Buddhist monk; Yogacara commentator; one of Silla's Four Great Writers",
     religion="Buddhism (Yogacara; later revered as founder of Goryeo Yugajong)",
     inst="Yongjangsa Temple, Namsan (Gyeongju)",
     india="Commented on Xuanzang/Dharmapala-derived Cheng Weishi Lun (Indian Yogacara thought); no India travel",
     korea="Silla monk; 52 works recorded, 5 extant",
     rel="INDIRECT", travel="NO", tsum="NULL",
     dir="INDIA_TO_KOREA", exch="RELIGIOUS;INTELLECTUAL",
     evid="Seong yusik non hakki (成唯識論學記) and Daeseung gisillon naeui yaktamgi (Awakening of Faith commentary); Beommanggyeong gojeokki (Brahma's Net Sutra)",
     sig="Key Silla interpreter of Indian-origin Yogacara texts; foundational figure claimed by early Goryeo Yugajong",
     conf="MEDIUM", status="VERIFIED",
     notes="Dates approximate; placed in King Gyeongdeok's reign (742-765) by tradition; some scholars date him later.",
     srcs=["encykorea_taehyeon","ucla_taehyeon"], date=D),

dict(id="P-0006", full="Marananta", variants="Mallananda; 摩羅難陀; 摩羅難陁",
     hangul="마라난타", hanja="摩羅難陀", indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="UNCERTAIN (Western Regions/Serindia; some scholars argue Indian; came via Eastern Jin China)", period="ANCIENT",
     role="Buddhist monk ('foreign monk' 胡僧)",
     religion="Buddhism",
     inst="First Baekje temple (Hansan, 385 CE)",
     india="If Indian (per some scholars, e.g., Lee Sang-ho 1960), the first Indian Buddhist to reach Korea; at minimum connected to Indian Buddhism via Central Asian monastic networks of the Jin period",
     korea="Arrived Baekje 384 (9th month, King Chimnyu's 1st year); received by the king; Buddhism 'began from this' (Samguk Sagi); temple built 385",
     rel="DIRECT", travel="YES",
     tsum="Came from Eastern Jin territory to Baekje by sea, 384 CE; no detailed itinerary preserved",
     dir="INDIA_TO_KOREA", exch="RELIGIOUS",
     evid="Samguk Sagi (sg_024r_0100_0030) and Samguk Yusa records; both mark 384 as the start of Baekje Buddhism",
     sig="Traditional founder of Baekje Buddhism; earliest documented Buddhist arrival in Korean history",
     conf="MEDIUM", status="VERIFIED",
      notes="Origin debated: db.history.go.kr (Samguk Sagi) notes '흔히 서역 출신으로 추정' with a minority view identifying him as an Indian monk (이상호 1960); encykorea describes him as '인도의 승려' (Gandhara-born per en-wiki); arrived via Eastern Jin. Sanskrit reconstruction of the name not attested in sources.",
      srcs=["sgs_marananta","sy_marananta","encykorea_marananta"], date=D),

dict(id="P-0007", full="Heo Hwang-ok", variants="Hŏ Hwang-ok; Huh Hwang-ok; 許黃玉; Queen of Suro of Geumgwan Gaya",
     hangul="허황옥", hanja="許黃玉", indian="(legendary) from 'Ayuta' (아유타), often equated with Ayodhya, India",
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="LEGENDARY (said to be from Ayuta; disputed: Ayodhya vs other readings)", period="ANCIENT",
     role="Queen consort of King Suro of Geumgwan Gaya (legendary)",
     religion="None recorded",
     inst="Geumgwan Gaya state",
     india="Legend: came by ship from Ayuta (often equated with Ayodhya, India) in 48 CE bearing gifts (twin-fish symbols); married King Suro",
     korea="Ancestress of the Gaya Heo clan; tomb at Gimhae royal tombs; centre of modern India-Korea memory culture",
     rel="UNCERTAIN", travel="UNCERTAIN",
     tsum="Legendary sea voyage from Ayuta in 48 CE; no contemporary record beyond Samguk Yusa/Garakguk-gi tradition (compiled centuries later)",
     dir="UNCERTAIN", exch="CULTURAL;RELIGIOUS",
     evid="Samguk Yusa (Garakguk-gi) narrative; modern movements (Kim Byung-mo's Ayodhya/twin-fish thesis) vs scholarly skepticism (Mohan, Kim Tae-sik: narrative reworked in Middle Silla/Goryeo)",
     sig="Symbol of India-Korea relations; also the most contested India-Korea connection - flagged as legend with historiographical caveats",
     conf="SPECULATIVE", status="LEGENDARY",
     notes="Scholarly debate: Kim Byung-mo's Ayodhya thesis vs Mohan/Kim Tae-sik skepticism (Goryeo-era narrative reworking); 'brother Jangyoo Hwasang' myth is a later addition (Ko Il-hong, SNU).",
     srcs=["oapen_heohwangok","snu_koilhong"], date=D),

dict(id="P-0008", full="Suro of Geumgwan Gaya", variants="King Suro; Kim Suro; 首露王; 金首露",
     hangul="수로왕", hanja="首露王", indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="LEGENDARY (founder of Geumgwan Gaya, now Gimhae, Korea)", period="ANCIENT",
     role="King (legendary founder)",
     religion="None (legend predates Buddhism)",
     inst="Geumgwan Gaya confederacy",
     india="Legendary: married Heo Hwang-ok, said to be from 'Ayuta' (often read as Ayodhya, India); six-egg origin myth",
     korea="Ancestor figure of the Gimhae Kim clan",
     rel="UNCERTAIN", travel="NO",
     tsum="Legend only; no physical journey recorded for Suro himself (the 'travel' is his legendary wife's); narrative survives via Garakguk-gi in Samguk Yusa",
     dir="UNCERTAIN", exch="CULTURAL",
     evid="Same corpus as Heo Hwang-ok; modern India ties derive from the marriage legend",
     sig="Founder-king of Geumgwan Gaya; central to the Ayodhya-connection myth debates",
     conf="SPECULATIVE", status="LEGENDARY",
     notes="No contemporary record; Samguk Yusa (13th c.) is the earliest source via Garakguk-gi. Legendary reign 42-199 CE.",
     srcs=["wiki_suro","sy_garak"], date=D),
]
