# -*- coding: utf-8 -*-
"""People data module 4/9: P-0027..P-0037 (Joseon/early modern). Compiled 2026-08-16 from verified web research."""
D = "2026-08-16"

PEOPLE_4 = [
dict(id="P-0027", full="Ch'oe Han-gi", variants="Choe Hangi; Choi Han-ki",
     hangul="최한기", hanja="崔漢綺", indian=None,
     birth=1803, birthp="YEAR", death=1877, deathp="YEAR",
     nat="KOREAN (Joseon)", period="EARLY_MODERN",
     role="Silhak philosopher; geographer; encyclopedist",
     religion="Confucian (with interest in Western sciences)",
     inst="NULL",
     india="Authored Jiguyŏn'gu (地球典要, 1857), a world-geography compendium introducing the Indian subcontinent to Korean readers, compiled chiefly from Xu Jiyu's Yinghuan zhilüe (瀛寰志略) and Wei Yuan's Haiguo tuzhi (海國圖志)",
     korea="Major Silhak figure; pre-modern Korean systematizer of world geography",
     rel="MEDIATED", travel="NO",
     tsum="Never travelled outside Korea",
     dir="INDIA_TO_KOREA", exch="INTELLECTUAL;CULTURAL",
     evid="EncyKorea entry on Jiguyŏn'gu (E0054094) confirming work, sources and scope; KCI scholarship (Sohn Yong-Taek)",
     sig="First complete Korean-language world geography including India's place in the Asian world",
     conf="HIGH", status="VERIFIED",
     notes="India appears as part of the world-region survey, not a standalone study.",
     srcs=["encykorea_jigujeonyo","kci_sohn"], date=D),

dict(id="P-0028", full="Yi Nŭng-hwa", variants="Yi Neunghwa; courtesy name Chahyŏn; pen names Kanjŏng, Sanghyŏn, Munŭng kŏsa",
     hangul="이능화", hanja="李能和", indian=None,
     birth=1869, birthp="DAY", death=1943, deathp="DAY",
     nat="KOREAN (Joseon -> colonial Korea)", period="MODERN",
     role="Historian; religious scholar; folklorist ('father of Korean religious studies'); school principal",
     religion="None (studied all religions comparatively)",
     inst="Hanseong Law-French School (principal); Chosŏn History Compilation Committee; Jungang Buddhist College lecturer",
     india="In Chosŏn Pulgyo T'ongsa (朝鮮佛敎通史, 1918) wrote the first comprehensive Korean Buddhist history tracing Korean Buddhism to its Indian origins; his comparative-religion framework (Paekkyo hoet'ong, 1912) engaged Indian religions",
     korea="National religious historian; pioneer of Korean religious studies",
     rel="MEDIATED", travel="NO",
     tsum="Visited Japan once on official inspection (1906-07); never India",
     dir="INDIA_TO_KOREA", exch="RELIGIOUS;INTELLECTUAL;ACADEMIC",
     evid="Chosŏn Pulgyo T'ongsa (Internet Archive scan); EncyKorea and AKS biographical entries",
     sig="Definitive early-20th-century account of Korean Buddhism's Indian-rooted history",
     conf="HIGH", status="VERIFIED",
     notes="Date discrepancy resolved: 1869-1943 per EncyKorea/AKS (Internet Archive's '1865-1945' is an error). Colonial-era record includes pro-Japanese designations.",
     srcs=["encykorea_yineunghwa","aks_yineunghwa","archive_tongsa"], date=D),

dict(id="P-0029", full="Ch'oe Nam-sŏn", variants="Choi Nam-sun; pen name Yuktang (六堂)",
     hangul="최남선", hanja="崔南善", indian=None,
     birth=1890, birthp="YEAR", death=1957, deathp="YEAR",
     nat="KOREAN (Korean Empire -> colonial Korea)", period="MODERN",
     role="Enlightenment thinker; historian; publisher; magazine editor",
     religion="None (wrote on Buddhism as national culture)",
     inst="T'aegŭk kwangmunhoe; Ch'ŏngch'un magazine",
     india="(a) Met Tagore at his Imperial University lecture in Tokyo, 1916 (first documented Korean-intellectual contact with Tagore); (b) in Chosŏn Pulgyo (1930, written for the Korean delegation to the Hawai'i Pan-Pacific Buddhist Youth Conference) argued Buddhism reached Korea directly from India/Xiyu via a 'northern route', independent of the China route; coined the scheme: India's introductory Buddhism, China's sectional Buddhism, Korea's conclusive Buddhism",
     korea="National enlightenment icon; Dangun/Bulham culture theory",
     rel="DIRECT", travel="NO",
     tsum="Studied in Japan (Tokyo); met Tagore there 1916; never visited India",
     dir="INDIA_TO_KOREA", exch="RELIGIOUS;INTELLECTUAL;CULTURAL",
     evid="budreview.com profile (Kim Young-jin 2013) quoting the India/Xiyu direct-route claim; beopbo.com on Chosŏn Pulgyo (2004); EncyKorea '통불교사상'",
     sig="Cast Korea as the culmination (not periphery) of India-originated Buddhism in world civilizational history",
     conf="HIGH", status="VERIFIED",
     notes="Beware the widespread 'Yuktang requested Song of the Defeated' myth - corrected by Hong Eun-taek (the request was made by Chin Hak-mun).",
     srcs=["budreview_choenamsun","beopbo_chosunbulgyo","encykorea_tongbulgyo"], date=D),

dict(id="P-0030", full="Rabindranath Tagore", variants="Robindronath Thakur (Bengali); Korean: 타고르/타골/타아골",
     hangul="라빈드라나트 타고르", hanja=None, indian="রবীন্দ্রনাথ ঠাকুর",
     birth=1861, birthp="YEAR", death=1941, deathp="YEAR",
     nat="INDIAN (Bengal)", period="MODERN",
     role="Poet; novelist; playwright; essayist; educator; first Asian Nobel laureate in Literature (1913)",
     religion="Brahmoism-influenced Hindu humanist universalism",
     inst="Visva-Bharati (Santiniketan)",
     india="India's national poet; the central Indian figure of Korea's literary imagination in the colonial era",
     korea="Signed a 6-line English message dated 1929-03-28 (Tokyo) later known as 'The Lamp of the East' (동방의 등불), delivered at Yokohama departure for the Korean people; published in Dong-a Ilbo Apr 1929, translated by Chu Yo-han; planned a Korea lecture in June 1929 (cancelled for health); sent 'The Song of the Defeated' to Chin Hak-mun in 1916 (published in Ch'ŏngch'un Nov 1917); met Ch'oe Nam-sŏn and Chin Hak-mun in Tokyo/Yokohama 1916",
     rel="DIRECT", travel="NO",
     tsum="Visited Japan five times (1916-1929) and China once (1924); never set foot in Korea despite two planned contacts; met Korean students in person in Tokyo/Yokohama 1916",
     dir="INDIA_TO_KOREA", exch="LITERARY;CULTURAL;POLITICAL",
     evid="Dong-a Ilbo archival record; Hong Eun-taek's studies (2012, 2014); Choi Seong-woo's rhetorical analysis (2022); Kim Ujo (2014) in 인도연구; 2011 bust at Daehak-ro (gift of the Indian government)",
     sig="The single most important Indian figure in Korean cultural memory of this period; his 'lamp' message became a national symbol of hope",
     conf="HIGH", status="VERIFIED",
     notes="The famous 15-line 'poem' is a patchwork: Tagore's actual message was a 6-line English note (an apology for declining the lecture request), translated into 4 Korean lines by Chu Yo-han (Apr 1929); Gitanjali #35 was appended and 'Korea' inserted in a closing line Tagore never wrote (likely from 세계명시선 1977); circulated in 2002/2003 textbooks and inscribed under the 2011 bust. First poem actually sent to Koreans: 'The Song of the Defeated' (Fruit-Gathering no. 85, Jan 1916).",
     srcs=["kyosu_tagore","joongang_tagore","koreatimes_tagore","kci_hong","kci_choi"], date=D),

dict(id="P-0031", full="Chin Hak-mun", variants="秦學文",
     hangul="진학문", hanja="秦學文", indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="KOREAN", period="MODERN",
     role="Student in Tokyo; translator",
     religion="NULL",
     inst="(Korean student community in Tokyo)",
     india="Met Tagore twice at Yokohama during Tagore's 1916 Japan visit; requested and received 'The Song of the Defeated'",
     korea="Translated and published the poem (under censorship-adjusted title 「쫓긴 이의 노래」) in Ch'ŏngch'un No. 11 (Nov 1917), believing it was composed 'especially for Korean youth' (actually a re-use of Fruit-Gathering no. 85)",
     rel="DIRECT", travel="NO",
     tsum="Korea -> Japan (Tokyo/Yokohama 1916); never India",
     dir="INDIA_TO_KOREA", exch="LITERARY;POLITICAL",
     evid="kyosu.net (citing Cho Yong-man 1982); koreatimes 2019; dongne.donga.com D-story 32 (2009)",
     sig="The first Korean to receive and publish a Tagore poem",
     conf="MEDIUM", status="VERIFIED", notes="NULL",
     srcs=["kyosu_tagore","koreatimes_tagore"], date=D),

dict(id="P-0032", full="Kim Ŏk", variants="Kim Uk; Kim Eok; pen name Anso (岸曙)",
     hangul="김억", hanja="金億", indian=None,
      birth=1896, birthp="APPROX", death=None, deathp="UNKNOWN",
      nat="KOREAN", period="MODERN",
      role="Poet; translator (pioneer of Korean modern poetry translation); magazine editor",
      religion="NULL",
      inst="Pyongyang Imunkwan publisher (기탄자리, 1923)",
      india="Produced the first full Korean translation of Tagore's Gitanjali (『기탄자리』, Pyongyang: Imunkwan, March 1923), the landmark of Indian literature's arrival in Korea; his renderings later analysed for characteristic mistranslations (e.g., 'thou'->'king' devotional shift)",
      korea="Founder-figure of Korean translation literature; introduced numerous world poets",
      rel="MEDIATED", travel="NO",
      tsum="No record of travel to India",
      dir="INDIA_TO_KOREA", exch="LITERARY;LINGUISTIC",
      evid="KCI scholarship: Jung Younghyo on Gitanjali/Kim Ŏk translation errors; Choi Dong-ho citing the March 1923 Pyongyang edition (National Assembly Library KINX2012046620; DBPia NODE01778075)",
      sig="India's Nobel poet enters Korean literature formally through his translation",
      conf="HIGH", status="VERIFIED",
      notes="Translation fact verified (Choi Dong-ho, NAL/DBPia: March 1923, Pyongyang Imunkwan; Jeong Ji-yong Literary Museum says April 1923 - minor discrepancy; a RidiBooks catalog entry lists a 1926 Imunkwan printing, likely reprint). Born 1896 (en-wiki; some sources 1895); abducted to North Korea during the Korean War; last trace at Cholsan cooperative farm, North Pyongan (1958).",
      srcs=["kci_jung","kci_choi","wiki_kimok"], date=D),

dict(id="P-0033", full="Jeong Ji-yong", variants="鄭芝溶",
     hangul="정지용", hanja="鄭芝溶", indian=None,
     birth=1902, birthp="YEAR", death=1950, deathp="YEAR",
     nat="KOREAN", period="MODERN",
     role="Poet",
     religion="NULL",
     inst="Hwimun High School (as student)",
     india="Translated 9 poems from Gitanjali in the school magazine Hwimun 창간호 (January 1923) - the earliest independently documented Korean Tagore translation, predating Kim Ŏk's full book (March 1923); later wrote 'I was crazy about Tagore's poems from India'",
     korea="Canonical modern Korean poet",
     rel="MEDIATED", travel="NO",
     tsum="No India travel",
     dir="INDIA_TO_KOREA", exch="LITERARY;LINGUISTIC",
      evid="KCI scholarship (Choi Dong-ho, ART001612260; National Assembly Library KINX2012046620 = same article); Jeong Ji-yong Literary Museum (Hwimun 창간호, Gitanjali poems 1-9)",
      sig="Earliest documented Korean translator of Tagore",
      conf="HIGH", status="VERIFIED",
      notes="Self-quote '나는 인도의 타고르 시에 미쳐 있었던 것이다' from his prose 「조택원 무용에 관한 것」 (per Choi Dong-ho's article).",
      srcs=["kci_choi","nanet_jiyong","oc_jiyong_museum"], date=D),

dict(id="P-0034", full="Han Yong-un", variants="Han Yong-woon; Buddhist name Manhae (萬海/卍海)",
     hangul="한용운", hanja="韓龍雲", indian=None,
     birth=1879, birthp="YEAR", death=1944, deathp="YEAR",
     nat="KOREAN", period="MODERN",
     role="Buddhist monk-poet; independence activist",
     religion="Buddhism (Seon; colonial-era reform)",
     inst="March 1st Movement signatory (33 national representatives)",
     india="Deeply engaged with Tagore: published the essay 「타골의 시를 읽고」('After Reading Tagore's Poem', 1926); KCI comparative studies document Gitanjali's influence on Nim-ŭi Ch'immuk (1926) alongside his critical distance - Han faulted Tagore's detachment from colonial resistance",
     korea="National poet and independence icon; Nim-ŭi Ch'immuk is a canonical work",
     rel="INDIRECT", travel="NO",
     tsum="No India travel",
     dir="INDIA_TO_KOREA", exch="LITERARY;RELIGIOUS;POLITICAL",
     evid="KCI comparative Han/Tagore study (ART002442623); Kim Ujo, 'Tagore's Perception of Joseon and Its Reception in Joseon', 인도연구 19(1), 2014",
     sig="Emblematic case of Korean creative absorption of Tagore's spiritual lyricism transformed into national resistance poetry",
     conf="HIGH", status="VERIFIED",
     notes="Dates widely documented; not re-pulled in pilot.",
     srcs=["kci_han_tagore","kci_kimujo"], date=D),

dict(id="P-0035", full="Yi Kwang-su", variants="Lee Kwang-su; pen name Ch'unwŏn (春園)",
     hangul="이광수", hanja="李光洙", indian=None,
     birth=1892, birthp="YEAR", death=1950, deathp="DAY",
     nat="KOREAN", period="MODERN",
     role="Novelist (Mujŏng, 1917); poet; essayist; independence activist; later pro-Japanese turn",
     religion="Converted seriously to Buddhism in the 1930s",
     inst="Waseda Univ. (philosophy); Tong-a Ilbo (editor-in-chief twice)",
     india="Published a review of Tagore's The Gardener (『타고르의 『원정』에 대하여』, Dong-a Ilbo, 1925-01-20), reading Tagore's poetic essence as yearning (사모함/그리워함) toward all living beings - praised by Kim Yun-sik as 'a review showing sharp understanding of Tagore'",
     korea="Father of the Korean modern novel; national-renovation theorist (Minjok kaejoron, 1922)",
     rel="INDIRECT", travel="NO",
     tsum="Lived in Japan and Shanghai; never India",
     dir="INDIA_TO_KOREA", exch="LITERARY;INTELLECTUAL",
     evid="Dong-a Ilbo review text quoted in peer-reviewed scholarship; Kim Yong-jik book chapter 'R. 타고르와 춘원 이광수'",
     sig="Verifiable instance of a leading Korean intellectual publicly engaging Indian poetry in the 1920s",
     conf="HIGH", status="VERIFIED",
     notes="No evidence of direct India contact or visit.",
     srcs=["encykorea_ikwangsu","kyungnam_pdf","kimyongjik_book"], date=D),

dict(id="P-0036", full="Chu Yo-han", variants="Ju Yo-han",
     hangul="주요한", hanja="朱耀翰", indian=None,
     birth=1900, birthp="YEAR", death=1979, deathp="YEAR",
     nat="KOREAN", period="MODERN",
     role="Poet (one of the first three modern Korean poets); editor-in-chief of Dong-a Ilbo",
     religion="NULL",
     inst="Dong-a Ilbo",
     india="As Dong-a Ilbo editor-in-chief, received Tagore's 6-line English message (1929) and rendered it into the now-famous 4 Korean lines '일즉이 아세아의 황금 시기에…' published in Dong-a Ilbo (April 2 or 3, 1929; sources conflict); his anthology Saebyŏk I records the transmission chain (Dong-a -> Yi Tae-ro -> Ch'oe Sŭng-man -> Nash -> Chandra Bose -> Tagore)",
     korea="Pioneer of Korean modern poetry; major newspaperman",
     rel="MEDIATED", travel="NO",
     tsum="NULL (no India travel recorded)",
     dir="INDIA_TO_KOREA", exch="LITERARY;LINGUISTIC",
     evid="kyosu.net (2012) reproducing his Saebyŏk I account; koreatimes (2019) confirming the 6-lines-to-4 translation",
     sig="His 4-line translation became Korea's most beloved national consolation text",
     conf="HIGH", status="VERIFIED",
     notes="Biographical dates commonly cited (1900-1979); not independently re-verified in pilot.",
     srcs=["kyosu_tagore","koreatimes_tagore","donga_tagore"], date=D),

dict(id="P-0037", full="Ham Sok-hon", variants="함석헌",
     hangul="함석헌", hanja="咸錫憲", indian=None,
     birth=1901, birthp="YEAR", death=1989, deathp="YEAR",
     nat="KOREAN", period="CONTEMPORARY",
     role="Quaker thinker; historian; educator; independence activist ('the Korean Gandhi')",
     religion="Quaker (Protestant); engaged Buddhism and Confucianism",
     inst="(independent scholar; later Ssangseong movement)",
     india="Studied and taught Gandhi's nonviolence philosophy from the colonial era onward; called '한국의 간디' (Korea's Gandhi); his thought mediated Gandhi's ideas into the Korean independence and democracy movements",
     korea="Major Korean civil-society thinker; influenced the 4.19 and democracy movements",
     rel="MEDIATED", travel="NO",
     tsum="No India travel documented",
     dir="INDIA_TO_KOREA", exch="POLITICAL;INTELLECTUAL;RELIGIOUS",
     evid="mkgandhi.org article on Ham Sok-hon as 'the Korean Gandhi'; Indian Express (2021) on Gandhi's influence on Korea's freedom struggle; Korean scholarship (Pak Hong-kyu's books)",
     sig="Principal bridge for Gandhi's ideas into Korea",
     conf="MEDIUM", status="VERIFIED",
     notes="Core activity spans colonial and post-1945 periods; pre-1945 documentary evidence of Gandhi reception needs primary-source verification.",
     srcs=["mkgandhi_ham","indianexpress_gandhi"], date=D),
]
