# -*- coding: utf-8 -*-
"""EVENTS + PERSON_EVENT tables. Compiled 2026-08-17 (Buddhist Bridges V3 v0.2).

EVENTS: dated contemporary India-Korea Buddhist developments. Contemporary
actors (Jung Won-ju, Abhijit Halder, Wonhaeng, Pomnyun) are recorded at event
level only unless independently documented as PEOPLE records.

EVENTS tuple:
(event_id, title, event_type, start_date, end_date, location_place_id,
 organizer_institution_ids, description, significance, evidence, confidence,
 status, source_keys)

PERSON_EVENT tuple (per user spec):
(person_id, event_id, role, evidence, confidence, notes)
roles: PARTICIPANT / ORGANIZER / SPEAKER / DELEGATION_LEADER /
       MONASTIC_LEADER / HOST / SCHOLAR / REPRESENTATIVE / TRANSLATOR
"""

EVENT_TYPES = {"PILGRIMAGE", "CONFERENCE", "EXHIBITION", "RELIC_TRANSFER",
               "MOU_AGREEMENT", "TEMPLE_FOUNDATION", "TEMPLE_DEDICATION",
               "DONATION", "FESTIVAL", "LECTURE_SERIES", "OTHER"}

PE_ROLES = {"PARTICIPANT", "ORGANIZER", "SPEAKER", "DELEGATION_LEADER",
            "MONASTIC_LEADER", "HOST", "SCHOLAR", "REPRESENTATIVE", "TRANSLATOR"}

# Event-level participants: contemporary actors documented at events but NOT
# carried as full PEOPLE records (per collection-plan rule). person_event rows
# may reference either a PEOPLE id (P-####) or an event-participant id (EP-####).
# (participant_id, name, hangul, role_hint, notes)
EVENT_PARTICIPANTS = [
("EP-0001","Jeongbeom sunim (정범 스님)","정범","REPRESENTATIVE",
 "Jogye 해외특별교구 교구장 직무대행 (acting head, overseas special diocese); attended GBS 2023 as official representative on behalf of 총무원장 (hyunbulnews_gbs2023)"),
("EP-0002","Munjong sunim (문종 스님)","문종","REPRESENTATIVE",
 "Jogye 국제교류위원/제전법단장 (international exchange committee member / propagation team head); attended 2nd GBS 2026 as representative of 총무원장 Jinwoo (tongbulgyo_gbs2026)"),
("EP-0003","Jinwoo sunim (진우 스님)","진우","MONASTIC_LEADER",
 "Jogye 총무원장 (supreme patriarch); congratulatory message read aloud at 2nd GBS 2026 by Munjong; represented at GBS 2023 by Jeongbeom (tongbulgyo_gbs2026; hyunbulnews_gbs2023)"),
("EP-0004","Wonhaeng sunim (원행 스님)","원행","DELEGATION_LEADER",
 "Jogye 총무원장; led the 150-person official delegation to the Bunhwangsa India dedication, May 2022 (hyunbulnews_bunhwangsa_2022)"),
("EP-0005","Jung Won-ju (정원주)","정원주","HOST",
 "President, Lay Buddhist Association of the Jogye Order; received the IBC Buddha statue at Bexpo 2026 (koreaherald_bexpo2026)"),
("EP-0006","Abhijit Halder","","ORGANIZER",
 "Director General, International Buddhist Confederation; presented the Buddha statue at Bexpo 2026; spoke at ICYBS 2025 (koreaherald_bexpo2026; ibcworld_icybs2025)"),
("EP-0007","Pomnyun sunim (법륜 스님)","법륜","MONASTIC_LEADER",
  "Jungto Society founder; leads the annual India pilgrimage program (jungto_india)"),
("EP-0008","Jugyeong sunim (주경 스님)","주경","REPRESENTATIVE",
  "Jogye 중앙종회의장 (chair, Central Council); represented the order at the Korea-India 50th anniversary cultural exchange, 21 Mar 2023 (ibulgyo_jogye50th_2023)"),
("EP-0009","Jang Jae-bok (장재복)","장재복","HOST",
  "ROK Ambassador to India; hosted the temple-food dinner at the ambassador's residence; praised the Sangwol pilgrimage for strengthening bilateral ties (ibulgyo_jogye50th_2023)"),
("EP-0010","Korean Buddhist delegation (6 members, 국제불교문제연구소 파견)","(대표단 6명)","PARTICIPANT",
  "Members unnamed in Dong-A 1982-01-19; dispatched by the International Buddhist Problems Research Institute (director 소장 김광태); toured Indian sacred sites, met PM Indira Gandhi, donated a Tripitaka Koreana facsimile at Nalanda; agreed Kelaniya-Bongeunsa sisterhood in Sri Lanka (donga_delegation_1982)"),
]

EVENTS = [
("EV-0001","Sangwol/Jogye walking pilgrimage India-Nepal","PILGRIMAGE","2023-02","2023-03","PL-0032","I-0022;I-0023",
 "108+ monastics of the ROK walking pilgrimage hosted by the Jogye Order with Sangwol Society; route Sarnath -> Shravasti via Bodh Gaya, Vulture Peak/Rajgir, Nalanda, Vaishali, Kushinagar, Lumbini, Kapilavastu; 1,167 km / 43 days (~200-strong delegation reported)",
 "Largest documented Korean monastic walking pilgrimage in India; PIB-documented",
 "PIB press release PRID=1896682; Korea Bizwire 2023-02-10; India Narrative 2023-03-22; The Federal",
 "HIGH","VERIFIED",["pib_sangwol2023","koreabizwire_sangwol2023","indianarrative_sangwol2023","thefederal_sangwol2023"]),
("EV-0002","Bexpo 2026 Buddhist exchange (IBC - Jogye lay)","EXHIBITION","2026-04-04","2026-04-04","PL-0024","I-0026",
 "At the Seoul International Buddhism Expo (Bexpo 2026), IBC Director General Abhijit Halder presented a Buddha statue to Jung Won-ju, president of the Lay Buddhist Association of the Jogye Order; cultural/spiritual cooperation agreed",
 "First documented IBC-Jogye lay exchange in Korea; institutional channel (INSTITUTIONAL)",
 "Korea Herald 2026-04-09 (Sanjay Kumar); Our Buddhism World 2026-04-10",
 "HIGH","VERIFIED",["koreaherald_bexpo2026","ourbuddhismworld_bexpo2026"]),
("EV-0003","2nd Global Buddhist Summit","CONFERENCE","2026-01-24","2026-01-25","PL-0027","I-0026",
  "Bharat Mandapam, New Delhi; IBC + Ministry of Culture; theme 'Collective Wisdom, United Voice and Mutual Coexistence'; 30+ countries, 800+ attendees. Korean participation CONFIRMED: Jogye international-exchange committee member / propagation team head Munjong sunim attended as representative of 총무원장 Jinwoo, whose congratulatory message was read aloud",
  "Second edition of India's flagship Buddhist summit; Jogye Order official participation documented",
  "Tongbulgyo News 2026-02-01; Buddhist Door Tea House 2026-01-18; IBC official event PDF; DD News 2026-01-18",
  "HIGH","VERIFIED",["tongbulgyo_gbs2026","buddhistdoor_gbs2026","ibcworld_gbs2026","ddnews_gbs2026"]),
("EV-0004","Jungto Society annual India pilgrimage program","PILGRIMAGE","2027-01-14","2027-01-30","PL-0010","I-0024",
 "Annual pilgrimage program (35th edition early 2026 implied; 36th: 14-30 Jan 2027, 16N17D, 500 participants, registration from 2026-05-25); Bodh Gaya region",
 "Largest recurring Korean lay pilgrimage to India",
 "Jungto Society official program page",
 "HIGH","VERIFIED",["jungto_india"]),
("EV-0005","Delhi University - BGICBS academic MOU","MOU_AGREEMENT","2026-04-23","2026-04-23","PL-0013","I-0012;I-0014",
 "Academic exchange agreement between the University of Delhi and the Bodh Gaya International College of Buddhist Studies (BGICBS, Chancellor: Ven. Buddhavara)",
 "Formalizes the main Indian university - Korean-led Buddhist college academic channel",
 "BTN (btn_buddhavara)",
 "MEDIUM","VERIFIED",["btn_buddhavara"]),
("EV-0006","Jogye delegation pilgrimage Sarnath -> Bodh Gaya","PILGRIMAGE","2022-05","2022-05","PL-0032","I-0022",
 "Jogye Order delegation pilgrimage from Sarnath to Bodh Gaya (Mahabodhi), May 2022",
 "Precursor delegation ahead of Bunhwangsa India dedication",
 "Beopbo 2022-05-20",
 "HIGH","VERIFIED",["beopbo_2022_jogye"]),
("EV-0007","Jogye pilgrimage to the 8 great sites + Nepal","PILGRIMAGE","2014-02-19","2014-03-04","PL-0010","I-0022",
 "13N14D Jogye Order pilgrimage to 8 great Buddhist sites + Nepal, including a visit to Yeoraesunwon (Korean-run temple at Bodh Gaya)",
 "Documents Yeoraesunwon's activity by 2014",
 "Jogye Order official news (jogyesa.kr num=3148)",
 "HIGH","VERIFIED",["jogyesa_2014_pilgrimage"]),
("EV-0008","Bunhwangsa India groundbreaking","TEMPLE_FOUNDATION","2020-03-28","2020-03-28","PL-0010","I-0015",
 "Groundbreaking of Bunhwangsa India, the Jogye Order's first temple in India, at Bodh Gaya; completion targeted 2022; project launched 2019-04 by the 36th administration (백만원력결집)",
 "Jogye Order's first permanent temple in India",
 "Ibulgyo 2020-02-06",
 "HIGH","VERIFIED",["ibulgyo_bunhwangsa_2020"]),
("EV-0009","Bunhwangsa India dedication (대웅보전 준공식)","TEMPLE_DEDICATION","2022-05","2022-05","PL-0010","I-0015;I-0022",
 "Dedication ceremony of the main hall (대웅보전) of Bunhwangsa India; 150-person Jogye official delegation ('official first pilgrimage' - 공식대표단 첫 순례) led by 총무원장 Wonhaeng; 3 years after the 2019 vow",
 "First official Jogye Order pilgrimage delegation to India; temple completion",
 "Hyunbul News 2022-05-19; Jogye Order news; Korea Times 2022-05-24",
 "HIGH","VERIFIED",["hyunbulnews_bunhwangsa_2022","buddhismorkr_bunhwangsa_2022","koreatimes_bunhwangsa_2022"]),
("EV-0010","Global Buddhist Summit 2023","CONFERENCE","2023-04-20","2023-04-21","PL-0027","I-0026",
  "First Global Buddhist Summit, Ashok Hotel, New Delhi (IBC + Ministry of Culture); ~30 countries, 500+ Buddhist leaders; PM Modi and Culture Minister Kishan Reddy attended; themes incl. environmental crisis/sustainability and preservation of the Nalanda Buddhist tradition. Korean participation CONFIRMED: Jogye 해외특별교구 교구장 직무대행 Jeongbeom sunim attended as official representative on behalf of 총무원장",
  "First edition of India's flagship Buddhist summit; Jogye Order official participation documented",
  "Hyunbul News 2023-04-27; IBC official event file; Drishti IAS daily news analysis",
  "HIGH","VERIFIED",["hyunbulnews_gbs2023","ibcworld_gbs2023","drishtiias_gbs2023"]),
("EV-0011","ICYBS 2025 (3rd Int'l Conf. of Young Buddhist Scholars)","CONFERENCE","2025-08-22","2025-08-22","PL-0027","I-0026",
  "Dr Ambedkar International Centre, Delhi; IBC + Ministry of Culture + Ministry of Social Justice & Empowerment; theme 'Wisdom Transmission in Buddha Dhamma in the 21st Century'; 4 panels + National Museum special presentation; key figures: Jangchup Choeden Rinpoche (SG IBC), Rana Pratap Singh (VC Gautam Buddha Univ.), K.T.S. Sarao, Abhijit Halder (DG IBC), Yeshi Dawa. Official IBC report names no Korean participant; PIB attendee list (India, Sri Lanka, Myanmar, Vietnam, Cambodia, Russia, Taiwan) contains no Korea",
  "Young-scholars track of the GBS cycle; Korean participation NOT DOCUMENTED",
  "IBC official event report; PIB PRID=2156138; DD India 2025-08",
  "MEDIUM","UNRESOLVED",["ibcworld_icybs2025","pib_icybs2025","ddindia_icybs2025"]),
("EV-0012","KBPF 2026 India pilgrimage (Dharamsala/Ajanta-Ellora/Sanchi)","PILGRIMAGE","2026-10-03","2026-10-11","PL-0039","I-0027",
  "8N9D India pilgrimage organized by the Korea Buddhism Promotion Foundation (대한불교진흥원): Dharamsala, Ajanta/Ellora caves, Sanchi Stupa; Air India; fees 4.59M KRW (10+ persons) / 4.09M (15+); registration open from 2026-07-02",
  "Distinct 2026 India pilgrimage by a Korean Buddhist foundation (not Jogye Order); answers the 'distinct 2026 pilgrimage' open question",
  "KBPF official notice 2026-07-02",
  "HIGH","VERIFIED",["kbpf_india2026"]),
("EV-0013","BBS Seon Meditation Tour 4 India-Nepal","PILGRIMAGE","2025-12-26","2026-01-04","PL-0010","I-0028",
  "8N10D India-Nepal pilgrimage organized by BBS (Buddhist Broadcasting System): Delhi, Lucknow, Varanasi, Bodh Gaya, Rajgir, Vaishali, Kushinagar, Shravasti, Lumbini, Pokhara, Kathmandu; led by 선업 스님 (former Jogye 포교원장); 3.42M KRW",
  "Korean Buddhist broadcaster-organized pilgrimage crossing into 2026; documents the 2026 pilgrimage landscape",
  "BBS overseas pilgrimage program page",
  "HIGH","VERIFIED",["bbs_or_kr_seonmyeong"]),
("EV-0014","Korea-India 50th anniversary cultural exchange (Jogye + ROK Embassy)","EXHIBITION","2023-03-21","2023-03-25","PL-0027","I-0022;I-0029",
  "Co-hosted by the Jogye Order (총무원장 Jinwoo) and the ROK Embassy in India: 21 Mar 2023 temple-food dinner (사찰음식 만찬) at ambassador Jang Jae-bok's residence (chef 정관스님; 어산종장 동환스님's 축원 화청); NGMA exhibition '부처님의 땅! 인도에서 한국문화를 만나다' (22 Mar - 30 Apr: 연등, media art, temple-stay photos); ~40 attendees incl. Apurva Chandra (Indian I&B Secretary) and Korean lawmakers; ambassador praised the Sangwol pilgrimage for strengthening bilateral ties",
  "First Jogye Order-ROK Embassy co-hosted cultural event in India; official diplomatic recognition of the Sangwol pilgrimage's value",
  "Ibulgyo 2023-03-22 (홍다영)",
  "HIGH","VERIFIED",["ibulgyo_jogye50th_2023"]),
("EV-0015","Korean Buddhist delegation to India (국제불교문제연구소)","PILGRIMAGE","1981-12","1982-01","PL-0031","I-0030",
  "6-member Korean Buddhist delegation dispatched by the International Buddhist Problems Research Institute (국제불교문제연구소) toured India's sacred sites (Dec 1981) and recently returned (reported 1982-01-19); met PM Indira Gandhi for ~30 minutes, presenting a Silla gold-crown replica and a Buddhist bell; visited Nalanda and donated a facsimile of the Haeinsa Tripitaka Koreana as research material for Korean Buddhist studies; in Sri Lanka agreed a sisterhood between Kelaniya Temple and Korea's Bongeunsa",
  "First documented institutional Korean Buddhist delegation to India in the post-war era; audience with the Indian PM; Tripitaka donation at Nalanda",
  "Dong-A Ilbo 1982-01-19 (Naver News Library); corroborated by Hyunbul News 2023-02-27",
  "HIGH","VERIFIED",["donga_delegation_1982","hyunbul_dongguk_nalanda"]),
("EV-0016","Dongguk University - Nalanda University MOU","MOU_AGREEMENT","2023-02-24","2023-02-24","PL-0009","I-0010;I-0031",
  "Academic cooperation agreement signed at Nalanda University between Dongguk University (president 윤재웅; 건학위원장 돈관 스님) and Nalanda University (Vice-Chancellor Sunaina Singh): joint education and research cooperation, plus a '순례' (pilgrimage) themed international conference and Korea-India 50th-anniversary activities",
  "First MOU between a Korean Buddhist university and the modern Nalanda University; revives the ancient Nalanda-Silla channel as contemporary institutional exchange",
  "Hyunbul News 2023-02-27",
  "HIGH","VERIFIED",["hyunbul_dongguk_nalanda"]),
("EV-0017","Enshrinement of Dhyānabhadra's relics at Hoeamsa","RELIC_TRANSFER","1370","1370","PL-0005","I-0003",
  "On King Kongmin's order (1370) a stupa enshrining the relics of the Indian master Dhyānabhadra (Jikong) was built at Hoeamsa, supervised by Naong Hyegeun - formally declaring Naong's succession of Jikong's lineage",
  "Earliest documented enshrinement of an Indian master's relics in Korea; material anchor of the Jikong lineage at the Nalanda-modeled Hoeamsa",
  "Dongguk University Buddhist Culture Portal (KBDI0001421): 1370 stupa on Kongmin's order, Naong supervised; corroborated by Hyunbul News 2017-01-26",
  "HIGH","VERIFIED",["buddhaland_hoeamsa_1370","hyunbul_jikong_2017"]),
("EV-0018","Return of Hoeamsa relics (Jikong/Naong + Buddha relics) from Boston MFA","RELIC_TRANSFER","2024-04","2024-05","PL-0005","I-0003",
  "Relics of Dhyānabhadra (Jikong) and Naong, enshrined with Buddha relics (Shakyamuni, Kashyapa, Dipankara) that Jikong brought from India, were returned to Korea from the Boston Museum of Fine Arts (illegally removed during the colonial era; acquired by the MFA 1939; return agreed 2023-24): delivered 2024-04-16, arrived in Korea 04-18, relocation rite at Jogye's Buddhist History & Culture Memorial Hall 04-19, re-enshrined at Hoeamsa 2024-05-19",
  "Modern completion of the 14th-century relic legacy: relics of Indian provenance (Buddha's relics carried from India by the Indian master Jikong) physically returned to the temple he founded",
  "Hankook Ilbo 2024-04-17; Ibulgyo 2024 (idxno=413032); Kyeonggi Ilbo 2024-04-19",
  "HIGH","VERIFIED",["hankookilbo_hoeamsa_relics_2024","ibulgyo_hoeamsa_relic_2024"]),
("EV-0019","Wang ocheonchukguk jeon first public display at National Museum of Korea","EXHIBITION","2010-12-18","2011-04-03","PL-0024","",
  "The BnF's Dunhuang manuscript of Hyecho's Wang ocheonchukguk jeon (往五天竺國傳) - the sole surviving 8th-century record of India by a Silla monk - was loaned to the National Museum of Korea for the '실크로드와 둔황: 혜초와 함께 하는 서역기행' special exhibition (18 Dec 2010 - 3 Apr 2011; manuscript on display until 17 Mar 2011 per the BnF's 3-month loan limit): the manuscript's first public display anywhere since Pelliot's 1908 Dunhuang discovery; a second BnF loan followed for the NMK exhibition Dec 2019 - Apr 2020",
  "World-first public display of Korea's oldest travel record of India; made Hyecho's 8th-century India pilgrimage tangible for the Korean public and scholars",
  "National Museum of Korea archive (2010-06-29); KBS News 2010-12-17; Hani 2019-10-19 (second loan)",
  "HIGH","VERIFIED",["museum_woj_2010","kbs_woj_2010","hani_woj_2019"]),
]

PERSON_EVENT = [
("P-0062","EV-0005","REPRESENTATIVE","BGICBS Chancellor (signatory institution's monastic head) per BTN (btn_buddhavara)","MEDIUM",
  "Chancellor of BGICBS, second signatory of the DU-BGICBS MOU; presence at signing inferred from role, not directly photographed/documented"),
("EP-0001","EV-0010","REPRESENTATIVE","Jogye 해외특별교구 교구장 직무대행; attended GBS 2023 as official representative on behalf of 총무원장 (hyunbulnews_gbs2023)","HIGH",
  "Official Jogye representative at the 1st Global Buddhist Summit"),
("EP-0002","EV-0003","REPRESENTATIVE","Jogye 국제교류위원/제전법단장; attended 2nd GBS 2026 as representative of 총무원장 Jinwoo (tongbulgyo_gbs2026)","HIGH",
  "Official Jogye representative at the 2nd Global Buddhist Summit"),
("EP-0003","EV-0003","SPEAKER","Congratulatory message read aloud by Munjong on behalf of 총무원장 Jinwoo (tongbulgyo_gbs2026)","HIGH",
  "Not physically present; message delivered via proxy"),
("EP-0004","EV-0009","DELEGATION_LEADER","Led the 150-person Jogye official delegation to the Bunhwangsa India dedication (hyunbulnews_bunhwangsa_2022)","HIGH",
  "총무원장 Wonhaeng led the 'official first pilgrimage' delegation"),
("EP-0005","EV-0002","HOST","Received the IBC Buddha statue as president of the Lay Buddhist Association of the Jogye Order (koreaherald_bexpo2026)","HIGH",
  "Host-side recipient at Bexpo 2026"),
("EP-0006","EV-0002","REPRESENTATIVE","Presented the Buddha statue as IBC Director General at Bexpo 2026 (koreaherald_bexpo2026)","HIGH",
  "Represented IBC at the Seoul exchange"),
("EP-0006","EV-0011","ORGANIZER","IBC Director General; spoke at ICYBS 2025 and announced broadening the conference to neighboring countries (ibcworld_icybs2025)","HIGH",
  "Organizer-side role at the 3rd ICYBS"),
("EP-0007","EV-0004","MONASTIC_LEADER","Jungto Society founder; leads the annual India pilgrimage program (jungto_india)","HIGH",
  "Spiritual leader of the Jungto pilgrimage program"),
("EP-0008","EV-0014","REPRESENTATIVE","Jogye 중앙종회의장; represented the order at the 50th-anniversary exchange (ibulgyo_jogye50th_2023)","HIGH",
  "Official Jogye representative at the Korea-India 50th anniversary cultural exchange"),
("EP-0009","EV-0014","HOST","ROK Ambassador to India; hosted the temple-food dinner at the ambassador's residence (ibulgyo_jogye50th_2023)","HIGH",
  "Host-side principal of the 50th-anniversary exchange"),
("EP-0010","EV-0015","PARTICIPANT","6-member delegation dispatched by 국제불교문제연구소; toured Indian sacred sites, met PM Gandhi, donated the Tripitaka facsimile at Nalanda (donga_delegation_1982)","HIGH",
  "Individual members unnamed in the Dong-A report; institute director Kim Gwang-tae (김광태) reported the activities"),
("P-0024","EV-0017","ORGANIZER","Naong supervised construction of the 1370 relic stupa on King Kongmin's order (buddhaland_hoeamsa_1370)","MEDIUM",
  "Per Dongguk Buddhist Culture Portal; the act publicly declared Naong's succession of Jikong's lineage"),
]
