# -*- coding: utf-8 -*-
"""People data module 7/9: P-0059..P-0067 (contemporary scholars/monks/translators). Compiled 2026-08-16."""
D = "2026-08-16"

PEOPLE_7 = [
dict(id="P-0059", full="Kaushal Kumar",
     hangul=None, hanja=None, indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="INDIAN", period="CONTEMPORARY",
     role="Associate Professor, Centre for Korean Studies, JNU",
     religion="NULL",
     inst="JNU, New Delhi",
     india="Indian scholar of Korean studies at JNU",
     korea="Korea Foundation fellow; AKS (한국학중앙연구원) predoctoral fellow; co-editor of 'Emerging Trends in Korean Studies in India' (2019; 2nd ed. 2024)",
     rel="DIRECT", travel="YES",
     tsum="Korea Foundation and AKS fellowships brought him to Korea",
     dir="KOREA_TO_INDIA", exch="ACADEMIC",
     evid="Fellowship record and edited volume in JNU profile",
     sig="Leading younger-generation Indian Korean-studies scholar",
     conf="HIGH", status="VERIFIED", notes="NULL",
     srcs=["jnu_kaushal"], date=D),

dict(id="P-0060", full="Ravikesh",
     hangul=None, hanja=None, indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="INDIAN", period="CONTEMPORARY",
     role="Professor, Centre for Korean Studies, JNU",
     religion="NULL",
     inst="JNU, New Delhi",
     india="Indian scholar of Korean studies at JNU",
     korea="Editor of 'Korean Studies in India & South Asia Vol-III' (Manak Publications, 2016); co-editor of '인도에서 한국어교육과 한국문화' (2018, with Kim Do-young)",
     rel="DIRECT", travel="UNCERTAIN",
     tsum="NULL - profile sparse; likely Korea visits for co-editing work, not documented",
     dir="BIDIRECTIONAL", exch="ACADEMIC",
     evid="Edited volumes with Korean co-editor",
     sig="Contributed to institutionalizing Korean studies in India",
     conf="MEDIUM", status="VERIFIED",
     notes="JNU profile is sparse; identity and publications verified, travel details unknown.",
     srcs=["jnu_ravikesh"], date=D),

dict(id="P-0061", full="Vyjayanti Raghavan",
     hangul=None, hanja=None, indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="INDIAN", period="CONTEMPORARY",
     role="Professor of Korean Language and Culture; Ex-Chairperson, Centre for Korean Studies, JNU; ICS faculty",
     religion="NULL",
     inst="JNU, New Delhi (until 2022); Institute of Chinese Studies (ICS)",
     india="Indian scholar who built the Korean language program at JNU since 2000",
     korea="MA in Korean History, Seoul National University; PhD, JNU (Disarmament Studies); recognized by Korean PM Hwang Gyo-ahn (2015) for contributions to Hangeul development; co-author/editor of 'India and Korea Through the Ages: Historical, Religious and Cultural'; author of 'Colonisation: A Comparative Study of India and Korea'",
     rel="DIRECT", travel="YES",
     tsum="Studied at Seoul National University (MA Korean History); multiple Korea engagements (PM recognition 2015)",
     dir="BIDIRECTIONAL", exch="ACADEMIC;LINGUISTIC;CULTURAL",
     evid="PM-level recognition for Hangeul promotion in India; extensive publications list",
     sig="The founding figure of Korean-language education at JNU (2000-2022) and most prominent Indian woman in Korean studies",
     conf="HIGH", status="VERIFIED", notes="NULL",
     srcs=["vyj_about","ics_vyj"], date=D),

dict(id="P-0062", full="Buddhavara (Ven.)", variants="붓다빠라 스님; Phra Buddhavara",
     hangul="붓다빠라", hanja=None, indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="KOREAN (South Korea; resident in India)", period="CONTEMPORARY",
     role="Buddhist monk; abbot of Bunhwangsa Temple India (분황사, Bodh Gaya); Chancellor of Bodh Gaya International College of Buddhist Studies; principal of Bodh Gaya International Meditation School; abbot at Sati Aramma (Kimhae)",
     religion="Buddhism (Korean Jogye Order; Theravada-oriented early-Buddhist meditation)",
     inst="Bunhwangsa India; Bodh Gaya International College of Buddhist Studies",
     india="Resident in Bodh Gaya leading Korean-led meditation training; signed academic-exchange MOU with University of Delhi (2026-04-23); honored in Korea as '인도 분황사 주지' (Beopbo, 2026-07-08)",
     korea="Foundational figure of Korean Buddhist institutions at Bodh Gaya; lecture circuits in Korea",
     rel="DIRECT", travel="YES",
     tsum="Lives between Korea and India (Kimhae Sati Aramma <-> Bodh Gaya); long-term presence at Bodh Gaya",
     dir="KOREA_TO_INDIA", exch="RELIGIOUS;ACADEMIC;CULTURAL",
     evid="Delhi University MOU; multiple Korean Buddhist-press reports",
     sig="Builder of the Korean Buddhist institutional bridgehead at Bodh Gaya",
     conf="MEDIUM", status="VERIFIED",
     notes="His own personal university study in India is NOT documented in cited sources; category is satisfied via long-term Indian residence and institutional leadership.",
     srcs=["btn_buddhavara"], date=D),

dict(id="P-0063", full="Hyoseok (Ven.)", variants="효석 스님",
     hangul="효석", hanja=None, indian=None,
     birth=1970, birthp="DECADE", death=None, deathp="UNKNOWN",
     nat="KOREAN (South Korea)", period="CONTEMPORARY",
     role="Bhikkhuni (nun); professor at Bongnyeongsa monastic college; attendant to preceptor Ven. Bongak",
     religion="Buddhism (Jogye Order bhikkhuni)",
     inst="Bongnyeongsa; Seoul Beopryongsa bhikkhuni hall",
     india="Studied cultural anthropology in India - MA from Pune University (뿌나대학), PhD from Delhi University (델리대학); studied yoga in India (certificate)",
     korea="Returned to Korea, teaches at Bongnyeongsa monastic college",
     rel="DIRECT", travel="YES",
     tsum="Full graduate study in India (Pune MA -> Delhi PhD) before ordination; returned with yoga credentials",
     dir="INDIA_TO_KOREA", exch="ACADEMIC;RELIGIOUS;CULTURAL",
     evid="Published profile essay documenting both degrees and India residence",
     sig="One of the few documented Korean nuns with Indian university doctorates",
     conf="HIGH", status="VERIFIED",
     notes="Article is a profile essay (Hyunbul News '모정불심' series) - single-source but detailed and first-person.",
     srcs=["hyunbul_hyoseok"], date=D),

dict(id="P-0064", full="Wookwan (Ven.)", variants="Wookwan Sunim; 우관스님",
     hangul="우관", hanja=None, indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="KOREAN (South Korea)", period="CONTEMPORARY",
     role="Bhikkhuni; founder/director of Mahayeon Temple Food Culture Center (Icheon); 2022 Jogye Order Temple-Food Master; inaugural director of Bongwonsa Temple-Food Culture Research Institute",
     religion="Buddhism (Jogye Order bhikkhuni; trained at Bongnyeongsa)",
     inst="Mahayeon Temple Food Culture Center; Bongwonsa",
     india="Studied at University of Delhi - MA in Buddhist Studies and PhD coursework (박사 수료), 5+ years in India; gave monthly Korean-language dharma talks for the Korean community in Delhi; volunteered at Sujata School, Bodh Gaya",
     korea="Korea's leading temple-food authority; international ambassador of Korean temple cuisine (New York/London Korean Cultural Centers, 2017-2019); author of 'Wookwan's Korean Temple Food' (2019, IBPA Benjamin Franklin Award silver)",
     rel="DIRECT", travel="YES",
     tsum="Entered Delhi University to remain in India legally; 5+ years of study + dharma teaching + Bodh Gaya volunteering; returned via Myanmar/Thailand pilgrimage",
     dir="BIDIRECTIONAL", exch="ACADEMIC;RELIGIOUS;CULTURAL;LINGUISTIC",
     evid="Jogye master designation 2022; Benjamin Franklin Award; Delhi University record",
     sig="The only bhikkhuni temple-food master in the Jogye Order; India-trained international communicator",
     conf="HIGH", status="VERIFIED",
     notes="Two sources diverge slightly on PhD completion (2010: '석·박사 모두 마침' vs 2022: '박사 수료') - newer source used as primary; discrepancy noted.",
     srcs=["ibulgyo_wookwan","cheonji_wookwan"], date=D),

dict(id="P-0065", full="Gakseong (Ven.)", variants="각성 스님; Gakseong Sunim",
     hangul="각성", hanja=None, indian=None,
     birth=1971, birthp="DECADE", death=2020, deathp="DAY",
     nat="KOREAN (South Korea)", period="CONTEMPORARY",
     role="Buddhist monk; abbot of Guryongsa (Seoul, 2010-2020); 17th Jogye Central Assembly member (2018-2020)",
     religion="Buddhism (Jogye Order)",
     inst="Guryongsa; Tongdosa lineage",
     india="Went to India in 1992 to study - University of Delhi, religious studies, 6 years; alone toured ~4,500 km of Buddhist pilgrimage sites in India",
     korea="Returned to Tongdosa monastic college; abbot of Guryongsa; social welfare leadership",
     rel="DIRECT", travel="YES",
     tsum="1992-1998 Delhi University study (6 years) plus 4,500 km solo pilgrimage across India's Buddhist sites",
     dir="INDIA_TO_KOREA", exch="ACADEMIC;RELIGIOUS",
     evid="BTN obituary/report; BBS obituary report",
     sig="Documented modern example of a Jogye monk with long India university study",
     conf="HIGH", status="VERIFIED",
     notes="Deceased 28 Sep 2020; two independent Buddhist-press obituaries corroborate.",
     srcs=["btn_gakseong","bbs_gakseong"], date=D),

dict(id="P-0066", full="Divik Ramesh",
     hangul=None, hanja=None, indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="INDIAN (Hindi-speaking)", period="CONTEMPORARY",
     role="Hindi poet and translator",
     religion="NULL",
     inst="Sahitya Akademi (project participant); Kaavyaalaya (poetry community)",
     india="Indian poet-translator of Korean poetry into Hindi",
     korea="(1) 'The day breaks O! India' - Korean poetess Choyi Kim Yang-Shik, original Korean + Hindi translation by Divik Ramesh, English by Jin Sup Kim (HathiTrust record); (2) Sahitya Akademi's 'Korean Poetry - Journey' (कोरियाई कविता-यात्रा); (3) 'Korea Bal Kavitha' (Korean children's poetry, 2017)",
     rel="MEDIATED", travel="UNCERTAIN",
     tsum="NULL - translation-based mediation; travel not documented",
     dir="KOREA_TO_INDIA", exch="LITERARY;LINGUISTIC",
     evid="Library catalogs and publisher listings of his Korean poetry translations",
     sig="Key figure bringing Korean poetry to Hindi readers via Sahitya Akademi",
     conf="HIGH", status="VERIFIED", notes="NULL",
     srcs=["hathi_divik","kaavyaalaya_divik"], date=D),

dict(id="P-0067", full="Dileep Jhaveri",
     hangul=None, hanja=None, indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="INDIAN (Gujarat)", period="CONTEMPORARY",
     role="Indian (Gujarati) poet and translator",
     religion="NULL",
     inst="NULL",
     india="Indian poet active in international poetry exchange",
     korea="Attended an international writers/poets gathering in Korea (1986); his poetry has been translated into Korean",
     rel="DIRECT", travel="YES",
     tsum="Traveled to Korea for poetry events (1986 documented); poetry circulated in Korean translation",
     dir="BIDIRECTIONAL", exch="LITERARY;CULTURAL",
     evid="ATUNIS profile documenting Korea conference participation and Korean translations of his work",
     sig="Part of the 1980s India-Korea poets' exchange circuit",
     conf="MEDIUM", status="VERIFIED",
     notes="His own translating of Korean works is NOT documented - hence 'other mediators' category; single-source profile.",
     srcs=["atunis_jhaveri"], date=D),
]
