# -*- coding: utf-8 -*-
"""People data module 6/9: P-0051..P-0058 (contemporary scholars/writers). Compiled 2026-08-16."""
D = "2026-08-16"

PEOPLE_6 = [
dict(id="P-0051", full="Ko Un", variants="Go Eun; 高銀; birth name Ko Un-tae (고은태, 高銀泰)",
     hangul="고은", hanja="高銀", indian=None,
     birth=1933, birthp="DAY", death=None, deathp="UNKNOWN",
     nat="KOREAN (South Korea)", period="CONTEMPORARY",
     role="Poet",
     religion="Buddhism (ordained monk 1952-1962)",
     inst="NULL",
     india="Travelled in India in the 1990s (Poetry Foundation bio); 1992 India visit (Authors Calendar); Feb 2019 New Delhi - Raza Biennale of Indian Poetry and talk at JNU (Korea Herald); guest of honor at 14th Kritya International Poetry Festival, read at its inauguration (online, 4-13 Jul 2021); novel Little Pilgrim (1992) set in India",
     korea="One of Korea's most celebrated living poets; official site koun.co.kr",
     rel="DIRECT", travel="YES",
     tsum="1990s India travels (1992 visit); Feb 2019 New Delhi (Raza Biennale; JNU talk); India themes surface in his poetry (Little Pilgrim, 1992); guest of honor at 14th Kritya International Poetry Festival (online, Jul 2021)",
     dir="BIDIRECTIONAL", exch="LITERARY;ACADEMIC",
     evid="Korea Herald 2023-01-13 exclusive on Ko Un's India/international career (Kritya 2021 guest of honor; New Delhi 2019; Mexico City 2018); Poetry Foundation bio; Authors Calendar (1992 visit)",
     sig="Korea's most translated contemporary poet; major cultural bridge between Korea and South Asia",
     conf="HIGH", status="VERIFIED",
     notes="Born 1 Aug 1933, Gunsan (ko-wiki; naver blog); birth name 고은태 (高銀泰) - earlier 'Yi Seon-il' variant dropped as unsupported. No India-specific travelogue/collection title identified despite searching (unresolved gap, not a contradiction).",
     srcs=["poetryfoundation_ko","koreaherald_kritya","koun","ko_wiki_koun","authorscalendar_koun"], date=D),

dict(id="P-0052", full="Pŏpchŏng", variants="Beopjeong; Beopjeong Sunim; 法頂; birth name Park Jae-cheol",
     hangul="법정", hanja="法頂", indian=None,
     birth=1932, birthp="YEAR", death=2010, deathp="YEAR",
     nat="KOREAN (South Korea)", period="CONTEMPORARY",
     role="Buddhist monk; essayist (author of 무소유 / 'Nothing to Possess')",
     religion="Buddhism (Korean Seon; Songgwangsa lineage)",
     inst="Songgwangsa lineage",
     india="Travelled to India in 1971; met Vinoba Bhave (Gandhian land-gift/ahimsa leader); Mahatma Gandhi's words quoted at the opening of his best-known essay collection 무소유",
     korea="One of the most beloved Korean Buddhist essayists of the 20th century",
     rel="DIRECT", travel="YES",
     tsum="1971 India trip - visited Vinoba Bhave's ashram; the encounter with Gandhian renunciation philosophy shaped his simplicity/renunciation teachings",
     dir="INDIA_TO_KOREA", exch="RELIGIOUS;LITERARY;INTELLECTUAL",
     evid="Bulkwang article (2024) on his India trip and Vinoba Bhave meeting; Gandhi quote opening 무소유",
     sig="Brought Gandhian renunciation-ethics into mainstream Korean Buddhist thought; 무소유 became a cultural phenomenon",
     conf="HIGH", status="VERIFIED",
     notes="Article also ties him to India's Buddhist sites (Sarnath/Bodh Gaya) pilgrimage culture.",
     srcs=["bulkwang_beopjeong","beopjeong_site"], date=D),

dict(id="P-0053", full="Lokesh Chandra", variants="Lokesh Chandra (son of Sanskritist Raghu Vira)",
     hangul=None, hanja=None, indian="लोकेश चंद्र",
     birth=1927, birthp="YEAR", death=None, deathp="UNKNOWN",
     nat="INDIAN", period="CONTEMPORARY",
     role="Indologist; Sanskritist; Vedic/Buddhist studies scholar; former Member of Parliament (Rajya Sabha)",
     religion="Buddhist-heritage scholarship (Buddhism specialist)",
     inst="International Academy of Indian Culture (Director)",
     india="India's foremost living Indologist; leading scholar of Buddhist Sanskrit and Korea's Buddhist heritage",
     korea="(1) Author of 'Morning Calm and The Pensive Beyond - Cultural Interflow Between India and Korea' (Aditya Prakashan, 2019); (2) Chapter 'Buddhism as the creative vision of Korea' in Cultural Horizons of India Vol. 2 (1990); (3) Ribbon-cutting at the Lotus Sutra exhibition in Seoul, Sept 2016, with Lee Soo-sung (former PM of Korea) and Chae Young Kim",
     rel="DIRECT", travel="YES",
     tsum="Visited Seoul Sept 2016 for the Lotus Sutra exhibition; decades of scholarship on Korea-India Buddhist cultural interflow",
     dir="INDIA_TO_KOREA", exch="ACADEMIC;CULTURAL;RELIGIOUS",
     evid="2019 monograph dedicated to India-Korea cultural interflow; Korean-themed chapter since 1990; participation in Seoul exhibition 2016",
     sig="Principal Indian scholar connecting India's Buddhist heritage with Korean Buddhist culture in the modern era",
     conf="HIGH", status="VERIFIED",
     notes="Korea connection anchored on three independent sources (book, collected-works chapter, event report).",
     srcs=["amazon_morningcalm","wisdomlib_choi","totetu_lotus","iats_lokesh"], date=D),

dict(id="P-0054", full="Jung Seung-suk", variants="Jeong Seung-seok; Chung Seung-suk",
     hangul="정승석", hanja=None, indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="KOREAN (South Korea)", period="CONTEMPORARY",
     role="Scholar of Indian philosophy (academic; Buddhist/Indian philosophy writing)",
     religion="NULL",
     inst="Dongguk University (MA 1980, PhD 1991 - Indian philosophy)",
     india="Career scholar of Indian philosophy; all degrees from Dongguk University (NOT India-trained)",
     korea="Contributes to Korean-language scholarship/publishing on Indian philosophy (Buddhist review, Beopbo, Kyobo author pages)",
     rel="INDIRECT", travel="UNCERTAIN",
     tsum="NULL - no documented India residence",
     dir="INDIA_TO_KOREA", exch="ACADEMIC;INTELLECTUAL",
     evid="Author profile and works on Indian philosophy (Kyobo); Buddhist-press articles",
     sig="Representative Korean academic of Indian philosophy in the domestic tradition",
     conf="HIGH", status="VERIFIED",
     notes="His MA/PhD are from Dongguk, not Delhi University - an India-trained status could NOT be documented; do not claim otherwise.",
     srcs=["budreview_jung","kyobo_jung"], date=D),

dict(id="P-0055", full="U Myeong-ju", variants="Woo Myung-ju; U Myung-ju",
     hangul="우명주", hanja=None, indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="KOREAN (South Korea)", period="CONTEMPORARY",
     role="Buddhist-studies researcher; former journalist (한겨레21 India correspondent); former Korean lecturer at University of Delhi",
     religion="Buddhism (lay scholar)",
     inst="Dongguk University Gyeongju (Buddhist studies researcher)",
     india="MA (c. 2001) and PhD in Buddhist Studies at University of Delhi; resided in Delhi; taught Korean at Delhi University; wrote '세계의 불교대학2: 인도 델리대학' (2019-03-19)",
     korea="Returned to Korea; researcher at Dongguk University Gyeongju",
     rel="DIRECT", travel="YES",
     tsum="Lived and studied in Delhi for her MA/PhD (c. 2001 onward); later worked as India correspondent and as Korean language lecturer at Delhi University",
     dir="BIDIRECTIONAL", exch="ACADEMIC;LINGUISTIC;JOURNALISM",
     evid="Her published first-hand article on Delhi University's Buddhist studies program (2019)",
     sig="Documented the Delhi University-Korean Buddhist connection for Korean readers; bridge figure",
     conf="HIGH", status="VERIFIED",
     notes="Lay scholar - placed in scholars category, NOT monastic.",
     srcs=["ggbn_umyeongju"], date=D),

dict(id="P-0056", full="Lee Jeong-ho", variants="Lee Jung-ho; Yi Jeong-ho",
     hangul="이정호", hanja=None, indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="KOREAN (South Korea)", period="CONTEMPORARY",
     role="Professor of Hindi, Hankuk University of Foreign Studies (HUFS); translator (Hindi->Korean)",
     religion="NULL",
     inst="HUFS (Hindi department)",
     india="Studied at Central Institute of Hindi; MA in Hindi Literature (JNU); PhD (Meerut University); author of 힌디-한국어사전 (Hindi-Korean Dictionary), 힌디문법, 아힌사, 베다 읽기, 마하트마 간디 평전, 인도와 한국의 단편문학 비교 연구; translated Tamas (Bhisham Sahni) into Korean; Hindi Sevi Samman (2009) from Indian President Pratibha Patil",
     korea="Korea's senior Hindi studies professor and India-literature translator",
     rel="DIRECT", travel="YES",
     tsum="Studied in India over years (Central Institute of Hindi, JNU, Meerut)",
     dir="BIDIRECTIONAL", exch="ACADEMIC;LINGUISTIC;LITERARY",
     evid="Hindi-Korean dictionary, Gandhi biography in Korean, Tamas translation, Presidential award",
     sig="Principal architect of Korean-language Hindi studies and Hindi<->Korean literary translation",
     conf="HIGH", status="VERIFIED",
     notes="Qualifies for both scholars and translators categories.",
     srcs=["kyobo_leejeongho"], date=D),

dict(id="P-0057", full="Pankaj Mohan", variants="पंकज मोहन",
     hangul=None, hanja=None, indian="पंकज मोहन",
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="INDIAN", period="CONTEMPORARY",
     role="Professor of Korean Studies, Academy of Korean Studies (한국학중앙연구원, AKS)",
     religion="NULL",
     inst="Academy of Korean Studies (Seongnam, Korea); formerly Tezpur University (India)",
     india="Indian scholar of Korea; delivered India-Korea relations lecture at Tezpur University",
     korea="Long-term professor at AKS teaching Korean studies in Korea; scholarly works on India-Korea cultural relations",
     rel="DIRECT", travel="YES",
     tsum="Indian academic resident in Korea (AKS, Seongnam) for his career; earlier India-based at Tezpur",
     dir="BIDIRECTIONAL", exch="ACADEMIC;INTELLECTUAL",
     evid="AKS professorship; Tezpur University lecture document; CEFIA Korea wiki entry",
     sig="One of India's senior Korean-studies scholars based in Korea",
     conf="HIGH", status="VERIFIED", notes="NULL",
     srcs=["aks_pankaj","tezpur_mohan"], date=D),

dict(id="P-0058", full="Neerja Samajdar", variants="Neerja Singh (JNU profile URL)",
     hangul=None, hanja=None, indian=None,
     birth=None, birthp="UNKNOWN", death=None, deathp="UNKNOWN",
     nat="INDIAN", period="CONTEMPORARY",
     role="Associate Professor, Korean Language, Centre for Korean Studies (CKS), JNU",
     religion="NULL",
     inst="Jawaharlal Nehru University (JNU), New Delhi",
     india="Indian professor teaching Korean language at JNU",
     korea="PhD in Korean Language Education from Seoul National University - first Indian to obtain it; Korean Government Scholarship recipient (2002)",
     rel="DIRECT", travel="YES",
     tsum="Studied in Seoul (SNU PhD, Korean Govt. Scholarship 2002)",
     dir="KOREA_TO_INDIA", exch="ACADEMIC;LINGUISTIC",
     evid="JNU CKS faculty profile documenting SNU PhD",
     sig="Pioneer of Korean-language pedagogy in India",
     conf="HIGH", status="VERIFIED", notes="NULL",
     srcs=["jnu_neerja"], date=D),
]
